/* QUANT TEST LAB — WEALTH MANAGEMENT TRACK Learn content.
   Same shape and depth standard as js/lessons.js (see concept 'c3' there for
   the reference bar). track:'wm' on every unit. */
(function (global) {
  'use strict';

  const L = [

    /* =============================== WM-A =============================== */
    {
      unit: 'WM-A', topic: 'Asset Allocation', title: 'Why allocation across asset classes matters more than picking within one', track: 'wm', concepts: [
        {
          id: 'wma1', name: 'Diversification across asset classes, not just across securities',
          primer: 'An "asset class" is a broad category of investment that shares similar fundamental characteristics and tends to respond to economic events in a similar way — the major asset classes a wealth manager works with are equities (ownership stakes in companies, via stocks), fixed income (loans to governments or companies, via bonds, which pay a scheduled return), cash and cash equivalents (highly liquid, very low-risk holdings like money market funds), real assets (physical property such as real estate or commodities), and alternative investments (private equity, hedge funds, and similar vehicles, covered in a later concept). "Asset allocation" is the decision of how to split a client\'s total wealth ACROSS these broad categories — for example, 60% equities, 30% fixed income, 10% cash — and it is a fundamentally different decision from "security selection," which is choosing WITHIN a category (picking individual stocks, or individual bonds). A large and consistently reproduced body of research in wealth management finds that the asset allocation decision explains the overwhelming majority of the variation in a diversified portfolio\'s long-run returns and risk — far more than which specific stocks or bonds are chosen within each category. Why does allocating ACROSS categories matter so much more than diversifying within just one? Because different asset classes respond differently — sometimes in OPPOSITE directions — to the same economic event: when a central bank raises interest rates sharply, bond prices typically fall (existing lower-rate bonds become less attractive) while certain equity sectors might hold up or even benefit; when a recession hits, equities often fall sharply while high-quality government bonds often RISE (investors flee to safety). Owning fifty different stocks, all from the same asset class, protects you only against risks specific to individual companies (a company-specific scandal, a single failed product) — it does nothing to protect against a risk that hits the ENTIRE equity asset class at once, like a broad market downturn. Only by holding asset classes that do not all move together can a portfolio meaningfully reduce its overall swings without simply lowering expected return in the process — recall from the earlier variance and correlation concepts that combining assets with LOW or NEGATIVE correlation shrinks portfolio-level risk below what either asset carries on its own.',
          core: 'Asset allocation (the split ACROSS broad categories like equities, fixed income, cash, real assets) explains the large majority of a diversified portfolio\'s long-run risk and return — far more than security selection (picking WITHIN a category). This works because different asset classes respond differently, sometimes oppositely, to the same economic event, allowing genuine risk reduction rather than just averaging.',
          when: 'Any question about why a portfolio should hold multiple asset classes, or about the relative importance of allocation versus individual security picks.',
          formulas: ['A portfolio\'s risk depends not just on each asset class\'s own volatility, but critically on the CORRELATION between asset classes (see the quant-track Portfolio Variance concept for the exact formula).', 'Diversifying within one asset class only removes security-SPECIFIC risk; it cannot remove risk that is common to the entire asset class.'],
          intuition: 'Picture two very different kinds of "protection": owning 50 stocks instead of 1 protects you if ONE company has bad news, but if the whole stock MARKET falls, all 50 fall together. Owning bonds and cash ALONGSIDE those stocks protects you against the market-wide event itself, because bonds and cash do not automatically fall just because stocks do.',
          examples: [
            { level: 1, text: 'A client holds 100% of their wealth in the stocks of 30 different technology companies. A broad downturn hits the technology sector specifically (e.g. rising interest rates hurting growth-stock valuations across the board). Despite owning 30 different companies, the client\'s portfolio falls sharply, because all 30 belong to the same asset class (equities) AND the same narrow sector — diversification within the stock picks did nothing to protect against a risk common to the whole group.' },
            { level: 2, text: 'A second client holds 60% in a broad mix of stocks across many sectors and countries, and 40% in high-quality government bonds. The same interest-rate-driven downturn hits stocks broadly, but government bonds (which this client also holds) often behave differently in this scenario — sometimes falling less, sometimes even rising, depending on the specific cause of the rate move. The blended portfolio experiences a smaller overall decline than an all-stock portfolio would, purely because of the asset-class diversification, independent of which specific stocks or bonds were chosen.' },
            { level: 3, text: 'A wealth manager is asked: "should I spend more effort selecting the very best individual stocks, or deciding the right mix of stocks versus bonds versus cash for my situation?" Given that research consistently shows asset allocation explains the large majority of long-run portfolio return and risk variation, the honest answer is that the allocation decision deserves the greater share of attention and effort — not because security selection is worthless, but because getting the broad mix right, matched to the client\'s own risk profile and goals, has historically mattered far more to long-run outcomes than which specific securities fill each slice.' }
          ],
          trap: 'Believing that owning many different individual stocks is enough diversification on its own — this only removes company-specific risk, not the broader risk shared by an entire asset class or sector, which is exactly the risk that allocating across DIFFERENT asset classes is designed to address.',
          checks: [
            { level: 1, q: 'What is the key difference between "asset allocation" and "security selection"?', options: ['They mean exactly the same thing', 'Asset allocation is the split ACROSS broad categories (equities, bonds, cash...); security selection is choosing WITHIN one category', 'Security selection always matters more for long-run returns', 'Asset allocation only applies to bonds'], a: 1, why: 'Allocation is the top-level mix across categories; selection is the more granular choice within any one category.' },
            { level: 1, q: 'Owning 50 different stocks from the same sector protects a client against which kind of risk?', options: ['Risk common to the whole sector', 'Risk specific to any one individual company', 'All possible risks equally', 'No risk at all'], a: 1, why: 'Diversifying within a single asset class/sector only removes company-specific risk, not risk shared across the whole group.' },
            { level: 2, q: 'Why can combining asset classes with LOW or NEGATIVE correlation reduce a portfolio\'s overall risk below either asset\'s own risk?', options: ['It cannot — combining assets always increases risk', 'Because when one asset class falls, a low/negatively correlated one may hold steady or rise, partially offsetting the decline', 'Because diversification always eliminates risk completely', 'Only if both asset classes have identical expected returns'], a: 1, why: 'This is the core mathematical result behind portfolio variance: assets that do not move together can partially cancel out each other\'s swings.' },
            { level: 2, q: 'A recession hits and equities fall sharply. What has historically often happened to high-quality government bonds in this scenario?', options: ['They always fall by the exact same amount as stocks', 'They have often held steady or risen, as investors seek safety', 'They become worthless', 'There is no typical pattern at all'], a: 1, why: 'A "flight to safety" during downturns has historically often supported high-quality government bond prices even as equities fall — though this relationship is not guaranteed in every scenario.' },
            { level: 3, q: 'Research consistently shows that, for a diversified portfolio, the majority of long-run return and risk variation is explained by:', options: ['Which individual stocks were picked', 'Market timing decisions', 'The asset allocation decision (the mix across broad categories)', 'The client\'s choice of financial adviser alone'], a: 2, why: 'This is one of the most consistently reproduced findings in the wealth management and institutional investing literature.' },
            { level: 3, q: 'A client says "I own 40 different stocks, so I am well diversified and do not need any bonds." What is the strongest response?', options: ['They are completely correct — 40 stocks is always enough', 'Owning many stocks only protects against company-specific risk; it does nothing against a broad, sector- or market-wide downturn, which allocating into other asset classes like bonds can help address', 'Bonds are never useful for any client', 'The number of stocks does not matter, only the total dollar amount invested'], a: 1, why: 'This directly restates the core lesson: within-asset-class diversification and across-asset-class allocation address different kinds of risk.' }
          ]
        },
        {
          id: 'wma2', name: 'Strategic versus tactical allocation, and why rebalancing is a discipline, not a prediction',
          primer: 'A "strategic asset allocation" is the long-run target mix of asset classes a wealth manager sets for a client — for example, "60% equities, 35% fixed income, 5% cash" — chosen to match that specific client\'s risk profile, goals and time horizon (covered in depth in the next concept), and meant to be held through ordinary market ups and downs rather than changed every time the news cycle shifts. A "tactical asset allocation" is a smaller, deliberate, temporary DEVIATION from that strategic target, based on a specific short-to-medium-term view about markets — for example, temporarily overweighting equities relative to the long-run target because valuations look unusually attractive, then returning to the strategic target once that view plays out or expires. Because markets move, a portfolio\'s ACTUAL mix drifts away from its strategic target purely mechanically over time, with no active decision required: if equities rally strongly while bonds are flat, the equity slice of the portfolio grows as a percentage of the total, even though nobody made a deliberate choice to increase equity exposure — the portfolio simply grew unevenly. "Rebalancing" is the periodic (or threshold-triggered) process of selling down the now-overweight asset classes and buying more of the now-underweight ones, to bring the portfolio\'s actual mix back in line with its strategic target. The single most important thing to understand about rebalancing is that it is fundamentally a RISK-CONTROL discipline, not a market-timing bet — a client who never rebalances after a strong equity rally ends up with a portfolio that is more equity-heavy (and therefore riskier) than they originally agreed to, purely by accident of market movement, exactly at a time when that additional risk was never actually chosen or approved. Rebalancing also has a well-documented behavioral side effect: because it mechanically requires selling some of what has recently gone UP and buying some of what has recently gone DOWN, it enforces a rough "buy low, sell high" discipline that counteracts the very natural, very costly emotional impulse to chase whatever has been performing best recently.',
          core: 'Strategic allocation is the long-run target mix; tactical allocation is a deliberate, temporary deviation from it based on a specific market view. Rebalancing brings a portfolio\'s actual (drifted) mix back to its strategic target — it is a risk-control discipline, not a prediction about markets, and it mechanically enforces selling recent winners and buying recent laggards.',
          when: 'Any question distinguishing long-run policy allocation from short-term tilts, or asking why/when a portfolio should be rebalanced.',
          formulas: ['Portfolio drift: if an asset class outperforms, its ACTUAL weight in the portfolio rises above its strategic TARGET weight, with no deliberate decision required.', 'Common rebalancing triggers: a fixed calendar schedule (e.g. quarterly or annually), or a threshold rule (rebalance whenever an asset class drifts more than some fixed percentage away from its target).'],
          intuition: 'Think of strategic allocation as the compass heading a ship is set to sail, and rebalancing as the periodic correction back onto that heading after ocean currents (market moves) have pushed the ship off course — the destination has not changed, only the accumulated, unintentional drift is being corrected.',
          examples: [
            { level: 1, text: 'A portfolio starts at the strategic target of 60% equities / 40% bonds. Over the next year, equities rise 25% while bonds are roughly flat. Without any rebalancing, the equity slice now makes up a noticeably larger share of the total portfolio than 60% — the portfolio has DRIFTED to be more equity-heavy (and riskier) than originally intended, purely from market movement, not from any deliberate decision.' },
            { level: 2, text: 'A wealth manager rebalances the drifted portfolio from the example above back to 60/40, by selling some of the now-oversized equity position and buying more bonds. Notice what this mechanically accomplishes: it sells some of what just went UP (equities, which had a great year) and buys more of what lagged (bonds) — the exact discipline of "sell high, buy low," achieved without anyone needing to correctly predict which asset class will do better NEXT year.' },
            { level: 3, text: 'A client asks: "the market has been volatile lately — should we move heavily into cash until things calm down, then move back into stocks once the news looks better?" This is a proposed TACTICAL move, and a fairly aggressive one, since it is based on a short-term prediction (that "things will calm down" and that the adviser can correctly time re-entry). Contrast this with rebalancing: rebalancing back to a strategic target requires no prediction about what markets will do next — it simply restores the previously agreed risk level. The tactical move described here carries real risk of getting the TIMING wrong on both the exit and the re-entry, a well-documented challenge even for professional investors.' }
          ],
          trap: 'Confusing rebalancing (restoring a previously agreed target, requiring no market prediction) with tactical allocation or market timing (deliberately betting on a short-term view). Also, failing to rebalance at all after a large market move, leaving a client unknowingly exposed to more risk than they actually agreed to.',
          checks: [
            { level: 1, q: 'A "strategic asset allocation" is:', options: ['A short-term bet based on a market prediction', 'The long-run target mix of asset classes, matched to the client\'s risk profile and goals', 'The same thing as picking individual stocks', 'A once-only decision that never needs revisiting for any reason'], a: 1, why: 'Strategic allocation is the durable long-run policy mix, distinct from short-term tactical tilts.' },
            { level: 1, q: 'Why does a portfolio\'s actual mix drift away from its strategic target over time, even with no active trading?', options: ['It never actually drifts if left alone', 'Different asset classes grow at different rates as markets move, mechanically shifting the proportions', 'Only bonds can cause drift', 'Drift only happens if the adviser makes a mistake'], a: 1, why: 'Uneven performance across asset classes purely mechanically shifts the portfolio\'s proportions over time, with no deliberate decision involved.' },
            { level: 2, q: 'Rebalancing is best described as:', options: ['A bet that markets will keep moving in the same direction', 'A risk-control discipline that restores the portfolio to its previously agreed target mix', 'Something that should only be done during a market crash', 'The same thing as tactical allocation'], a: 1, why: 'Rebalancing corrects unintentional drift back to the agreed strategic target — it is not a market prediction.' },
            { level: 2, q: 'After a strong equity rally, a portfolio has drifted from 60/40 to 70/30 (equities/bonds). What does rebalancing back to 60/40 require doing?', options: ['Buying more equities and selling bonds', 'Selling some equities and buying more bonds', 'Doing nothing at all', 'Selling the entire portfolio'], a: 1, why: 'Restoring the target requires trimming the now-oversized (equity) position and adding to the now-undersized (bond) position.' },
            { level: 3, q: 'Why is rebalancing sometimes described as automatically enforcing "buy low, sell high"?', options: ['It does not — rebalancing has no relationship to buying or selling patterns', 'Because it mechanically sells asset classes that have recently risen (relatively "high") and buys ones that have lagged (relatively "low"), without requiring any prediction', 'Because it always involves buying whatever is currently cheapest globally', 'Because it eliminates all investment risk'], a: 1, why: 'Rebalancing trims recent outperformers and adds to recent underperformers purely by restoring fixed target weights — a rough, automatic version of the classic advice.' },
            { level: 3, q: 'A client proposes moving entirely to cash now, planning to move back into stocks once "the news looks better." What kind of decision is this, and what is its main risk?', options: ['This is rebalancing, and it carries no risk', 'This is a tactical, market-timing move, and it carries real risk of mistiming both the exit and the re-entry', 'This is required by the client\'s strategic allocation', 'This is illegal for a wealth manager to discuss'], a: 1, why: 'A large, prediction-based shift like this is a tactical bet, not a restoration of an agreed target — and correctly timing both the exit and re-entry is notoriously difficult, even for professionals.' }
          ]
        }
      ]
    },

    /* =============================== WM-B =============================== */
    {
      unit: 'WM-B', topic: 'Suitability & Risk Profiling', title: 'Matching a portfolio to the client it is actually for', track: 'wm', concepts: [
        {
          id: 'wmb1', name: 'Risk tolerance, risk capacity, and time horizon: three different things that must all agree', track: 'wm',
          primer: '"Suitability" is the principle — and, in most jurisdictions, the legal and regulatory requirement — that an investment recommendation must actually be appropriate for the SPECIFIC client receiving it, rather than simply being a "good investment" in some generic, one-size-fits-all sense. Getting suitability right requires carefully separating three related but genuinely DIFFERENT concepts that are very easy to blur together. "Risk tolerance" is PSYCHOLOGICAL: how much investment volatility and potential loss a client can emotionally withstand without panicking and making a poor decision (like selling everything during a downturn, locking in losses) — it is measured through conversation, questionnaires, and understanding the client\'s past behavior during previous market stress. "Risk capacity" is FINANCIAL and objective: how much investment risk a client can afford to take, given their actual financial circumstances — their income stability, the size of their emergency reserves, how soon they will need to draw on the portfolio, and how catastrophic a large loss would actually be to their real-world financial security. "Time horizon" is simply how long the money is expected to remain invested before it is needed — a retirement portfolio for a 30-year-old has a vastly longer time horizon than a house down-payment fund needed in 18 months, even if the two clients happen to have identical account sizes. The reason distinguishing all three matters so much is that they do not always point in the same direction, and when they conflict, a wealth manager must generally defer to the MOST CONSERVATIVE (most restrictive) of the three, not simply pick whichever one is most convenient: a client might have high risk TOLERANCE (they say they are comfortable with big swings, having read a lot about investing) but low risk CAPACITY (they have little savings cushion and would face genuine financial hardship from a large loss) — in this case, capacity should generally constrain the recommendation, regardless of the client\'s stated emotional comfort with risk, because the objective financial consequence of a bad outcome is what suitability rules are ultimately designed to protect against.',
          core: 'Risk tolerance (psychological comfort with volatility), risk capacity (objective financial ability to absorb loss), and time horizon (how long until the money is needed) are three genuinely different inputs to a suitable recommendation. When they conflict, the most conservative of the three should generally constrain the recommendation — a client\'s stated comfort with risk (tolerance) does not override a genuine inability to financially withstand a loss (capacity).',
          when: 'Any question about matching a portfolio to a client, or distinguishing why a client\'s stated risk appetite might not be the deciding factor in a recommendation.',
          formulas: ['Suitable recommendation ≈ the intersection (most conservative binding constraint) of risk tolerance, risk capacity, and time horizon — not simply the client\'s stated preference alone.', 'A shorter time horizon generally argues for a more conservative allocation, all else equal, since there is less time to recover from a downturn before the money is needed.'],
          intuition: 'Risk tolerance is "how much risk do you WANT to take, emotionally"; risk capacity is "how much risk can you actually AFFORD to take, financially" — a wealth manager\'s job is to make sure a client\'s portfolio never asks them to take on more risk than their capacity can genuinely support, even if their stated tolerance would allow it.',
          examples: [
            { level: 1, text: 'A 28-year-old client is saving for retirement, 35+ years away, has a stable job, a healthy emergency fund, and says they are comfortable with significant short-term volatility. Time horizon: long. Risk capacity: high (stable income, cushion in place, decades to recover from any downturn). Risk tolerance: high (stated comfort with volatility). All three align, supporting a growth-oriented, equity-heavy allocation.' },
            { level: 2, text: 'A 62-year-old client plans to retire and start drawing on their portfolio in 3 years. They say they are "not worried at all" about volatility and want an aggressive, all-equity portfolio. Time horizon: short-to-medium (money needed soon). Risk capacity: limited (a large market drop shortly before or during retirement could permanently impair their ability to fund retirement spending — there may not be enough time to recover before withdrawals begin). Even though stated risk TOLERANCE is high, the short time horizon and limited capacity should generally constrain the recommendation toward a more conservative mix than the client\'s stated comfort alone would suggest.' },
            { level: 3, text: 'A client has substantial financial resources (very high risk capacity — a large loss would not meaningfully affect their lifestyle) and a long time horizon, but describes significant anxiety about market volatility based on a bad personal experience during a past downturn (low stated risk tolerance). Here, capacity and horizon would technically SUPPORT an aggressive allocation, but a suitable recommendation must also respect the client\'s genuine psychological tolerance — recommending a portfolio so volatile that the client is likely to panic-sell during the next downturn (locking in real losses at the worst possible time) is not actually suitable, even though it might look "optimal" on paper from a pure capacity standpoint. This illustrates why all three factors matter together, not just the two that happen to be favorable.' }
          ],
          trap: 'Treating a client\'s STATED comfort with risk (tolerance) as automatically sufficient justification for an aggressive recommendation, without separately checking whether their actual financial circumstances (capacity) and time horizon can genuinely support that level of risk — the three factors are independent and a suitable recommendation must respect all three, generally deferring to the most conservative one when they conflict.',
          checks: [
            { level: 1, q: 'Risk TOLERANCE is best described as:', options: ['How much investment loss a client could financially survive', 'How much investment volatility a client can psychologically withstand without panicking', 'How long the money will stay invested', 'The client\'s account size'], a: 1, why: 'Tolerance is the psychological/emotional dimension of risk appetite, distinct from the financial (capacity) and time (horizon) dimensions.' },
            { level: 1, q: 'Risk CAPACITY is best described as:', options: ['How the client feels about market volatility', 'The client\'s objective, financial ability to absorb a loss without real hardship', 'How long until retirement', 'The client\'s favorite asset class'], a: 1, why: 'Capacity is an objective financial measure, based on income, savings cushion, and need for the funds — not on feelings.' },
            { level: 2, q: 'A client has high stated risk tolerance but low risk capacity (little financial cushion). What should generally happen?', options: ['Always follow the stated tolerance since the client knows best', 'The recommendation should generally be constrained by the lower risk capacity, since a bad outcome would cause genuine financial hardship', 'Capacity is irrelevant if tolerance is high', 'Split the difference exactly evenly with no further analysis'], a: 1, why: 'Suitability rules exist to protect clients from financial harm; when capacity and tolerance conflict, the more conservative (constraining) factor should generally govern.' },
            { level: 2, q: 'Why does a SHORTER time horizon generally argue for a more conservative allocation?', options: ['Shorter time horizons always mean the client is older', 'There is less time to recover from a market downturn before the funds are actually needed', 'Time horizon has no effect on suitable allocation', 'A shorter horizon always means less money is available'], a: 1, why: 'A downturn shortly before funds are needed leaves little or no time for a subsequent recovery, unlike a downturn early in a long horizon.' },
            { level: 3, q: 'A client has very high risk capacity and a long time horizon but describes real anxiety about volatility. What is the most suitable approach?', options: ['Ignore the stated anxiety entirely and recommend the most aggressive allocation their capacity technically supports', 'Take the psychological discomfort seriously too — an overly aggressive portfolio risks the client panic-selling during a downturn, locking in real losses', 'Refuse to manage the account at all', 'Automatically recommend an all-cash portfolio regardless of capacity or horizon'], a: 1, why: 'A technically "optimal" allocation that ignores genuine psychological tolerance can lead to poorly-timed panic selling, which is a real, practical risk suitability must account for.' },
            { level: 3, q: 'Why might a wealth manager generally defer to the MOST CONSERVATIVE of tolerance, capacity, and horizon when they conflict, rather than an average of the three?', options: ['Regulation requires always choosing the average', 'Because allowing any one dimension to be overridden risks a genuinely unsuitable outcome for the client in exactly the scenario where that dimension is binding', 'The most conservative option is always the most profitable for the adviser', 'There is no real reason — any of the three works equally well'], a: 1, why: 'Each dimension represents a distinct kind of real risk to the client (financial hardship, emotional panic-selling, insufficient recovery time) — ignoring the binding constraint defeats the purpose of assessing all three in the first place.' }
          ]
        },
        {
          id: 'wmb2', name: 'The Investment Policy Statement, and guarding against the client\'s own worst instincts',
          primer: 'An "Investment Policy Statement" (almost always abbreviated IPS) is a written document, agreed between a wealth manager and a client, that formally records the client\'s goals, time horizon, risk tolerance and capacity, any special constraints (such as needing to avoid certain investments for personal, religious, or liquidity reasons), and — critically — the resulting strategic asset allocation target and the rules for how and when the portfolio will be rebalanced. The IPS exists to solve a very real, very common problem in wealth management: a client\'s feelings about risk are NOT stable over time — they tend to shift with recent market performance, becoming more comfortable with risk after a period of strong returns (exactly when caution might be warranted, since valuations may be stretched) and less comfortable with risk after a period of losses (exactly when staying the course, or even adding to positions, might be the historically better choice). Without a written, pre-agreed reference point, it becomes very easy for a client (or even an adviser, under pressure from an anxious client) to make emotionally-driven changes to a portfolio at precisely the worst possible moments — this pattern of behavior, buying after prices have already risen and selling after they have already fallen, is one of the most well-documented and costly mistakes in all of investing, and it is the OPPOSITE of the disciplined "buy low, sell high" behavior that rebalancing enforces. The IPS acts as a pre-committed anchor, agreed upon during a calmer, more rational moment, that both the client and the adviser can return to during periods of market stress or euphoria — when a client calls during a sharp downturn wanting to sell everything, the IPS provides a concrete, previously-agreed basis for the conversation ("we agreed your time horizon and capacity support staying invested through downturns like this one; has anything about your actual financial situation changed, or is this a reaction to short-term market movement?") rather than an in-the-moment negotiation driven purely by fear.',
          core: 'An Investment Policy Statement is a written, pre-agreed record of a client\'s goals, risk profile, and target allocation, created specifically to serve as a stable anchor against the well-documented tendency for investor sentiment (and resulting bad decisions) to swing with recent market performance — becoming overconfident after gains and fearful after losses, exactly backwards from a disciplined approach.',
          when: 'Any question about why a formal written investment policy matters, or about how to handle a client wanting to abandon their strategy during a market swing.',
          formulas: ['An IPS typically documents: goals and constraints, time horizon, risk tolerance and capacity, target strategic asset allocation (with acceptable ranges), and the rebalancing policy/triggers.'],
          intuition: 'Think of the IPS like a sailing plan filed before a long voyage, written while the crew is calm and thinking clearly — during a storm is exactly the wrong time to be deciding the destination for the first time, but it is a very good time to consult the plan that was already agreed upon before the storm began.',
          examples: [
            { level: 1, text: 'A client and adviser agree an IPS in a calm market: 65% equities, 30% bonds, 5% cash, to be rebalanced whenever any asset class drifts more than 5 percentage points from target. Six months later, after a strong equity rally, equities have drifted to 74% of the portfolio. The IPS provides a clear, pre-agreed trigger: rebalance back toward 65%, regardless of how good the recent equity returns have felt.' },
            { level: 2, text: 'During a sharp market downturn, an anxious client calls wanting to move entirely to cash. The adviser refers back to the IPS: it documents that this client has a 20-year time horizon and high risk capacity, and that the strategic allocation was specifically designed to be held through downturns of this magnitude. The adviser uses this as the basis for a calmer conversation, asking whether the client\'s actual underlying financial circumstances have changed (which might genuinely justify revisiting the IPS) or whether this is a short-term emotional reaction to market movement (which the IPS was specifically designed to help withstand).' },
            { level: 3, text: 'A client\'s circumstances genuinely CHANGE — they unexpectedly lose their job and now need to draw on the portfolio for living expenses much sooner than originally planned. Does the IPS mean "never change the allocation, no matter what"? No — the IPS should be revisited and updated when a client\'s actual goals, time horizon, or risk capacity genuinely change; what it protects against is changing the allocation based purely on a REACTION to short-term market movement, not against updating it in response to a genuine change in the client\'s real financial situation. Distinguishing "my circumstances changed" from "the market scared me" is precisely the judgment the IPS is designed to help make explicit.' }
          ],
          trap: 'Treating the IPS as an unchangeable document that can never be revisited under any circumstances — the IPS should absolutely be updated when a client\'s GENUINE goals, time horizon, or financial circumstances change; what it specifically guards against is changing strategy purely in emotional REACTION to short-term market movement, which is a very different thing from a genuine change in circumstances.',
          checks: [
            { level: 1, q: 'An Investment Policy Statement is best described as:', options: ['A marketing brochure for the wealth management firm', 'A written, pre-agreed record of a client\'s goals, risk profile, and target allocation', 'A legal requirement only for institutional investors, never individuals', 'A prediction of future market returns'], a: 1, why: 'The IPS formally documents the agreed plan, serving as a stable reference point over time.' },
            { level: 1, q: 'Why do investors\' feelings about risk tend to shift with recent market performance in a way that can be harmful?', options: ['They do not shift at all — risk tolerance is always perfectly stable', 'Investors tend to become MORE comfortable with risk after gains (when caution may be warranted) and LESS comfortable after losses (when staying invested may be better) — backwards from disciplined behavior', 'Feelings about risk always move in the helpful direction', 'This only affects institutional investors, never individuals'], a: 1, why: 'This well-documented pattern is exactly backwards from "buy low, sell high," and is a primary reason a pre-agreed IPS is valuable.' },
            { level: 2, q: 'A client wants to sell everything during a downturn, purely out of short-term fear, with no change in their actual financial circumstances. What is the IPS\'s primary role here?', options: ['To force the adviser to comply with the client\'s immediate request with no discussion', 'To serve as a pre-agreed anchor for a calmer conversation about whether anything has genuinely changed', 'To automatically liquidate the account', 'The IPS has no relevant role in this situation'], a: 1, why: 'The IPS provides a concrete, previously-agreed basis for evaluating whether the request reflects a genuine change in circumstances or a short-term emotional reaction.' },
            { level: 2, q: 'What does a typical IPS document?', options: ['Only the client\'s favorite stocks', 'Goals, time horizon, risk tolerance and capacity, target allocation, and rebalancing policy', 'Only tax filing information', 'Nothing related to asset allocation'], a: 1, why: 'These are the core components that make the IPS a comprehensive, useful reference for future decisions.' },
            { level: 3, q: 'A client unexpectedly loses their job and now needs to draw on the portfolio much sooner than planned. Should the IPS be revisited?', options: ['No, the IPS should never be changed under any circumstances', 'Yes — this is a genuine change in the client\'s actual circumstances (time horizon and capacity), which is exactly the kind of situation that should prompt an IPS update', 'Only if the market happens to be doing well at the time', 'The IPS is irrelevant to employment status'], a: 1, why: 'The IPS guards against reacting to short-term market noise, not against updating the plan when a client\'s real, underlying situation genuinely changes.' },
            { level: 3, q: 'What is the key distinction between a situation that SHOULD prompt revisiting the IPS and one that should not?', options: ['There is no meaningful distinction — any client request should be followed immediately', 'A genuine change in the client\'s actual goals, time horizon, or financial capacity should prompt a review; a purely emotional reaction to short-term market movement, with no underlying change, should not', 'Only the adviser\'s convenience matters', 'The IPS should be revisited every single day regardless of any change'], a: 1, why: 'This distinction — real change in circumstances versus emotional reaction to market noise — is the central practical judgment the IPS is designed to support.' }
          ]
        }
      ]
    },

    /* =============================== WM-C =============================== */
    {
      unit: 'WM-C', topic: 'Tax & Liquidity Planning', title: 'Two constraints that reshape a portfolio beyond pure risk and return', track: 'wm', concepts: [
        {
          id: 'wmc1', name: 'Tax-efficient asset location: the same portfolio can end up with more (or less) after-tax wealth', track: 'wm',
          primer: 'Two clients can hold the EXACT same underlying investments — the same stocks, the same bonds, in the exact same proportions — and still end up with meaningfully different amounts of after-tax wealth over time, purely because of a decision called "asset location" (not to be confused with "asset allocation," the earlier concept about WHICH asset classes to hold — location is about WHERE, in which type of account, to hold them). Many wealth management clients have access to more than one type of investment account with different tax treatment: a standard "taxable" brokerage account (investment gains and income are taxed as they are realized, in the year they occur); a "tax-deferred" retirement account (contributions or growth are not taxed until money is eventually withdrawn, often years or decades later); and, in some jurisdictions, a "tax-exempt" account (money grows and can be withdrawn with no further tax at all, under specific rules). Different TYPES of investment income are taxed differently — interest income from bonds is often taxed at a higher rate, and more frequently (every year it is received), than long-term capital gains from stocks, which are often taxed at a lower rate and only when the position is actually SOLD, deferring the tax bill potentially for years. "Asset location" is the strategy of deliberately placing the more tax-inefficient assets (ones generating frequently-taxed income, like most bonds) inside tax-advantaged accounts (deferred or exempt), while placing more tax-efficient assets (ones generating occasional, deferrable, often lower-taxed capital gains, like many stocks) inside the ordinary taxable account — this way, the type of income that would otherwise be taxed most heavily and most frequently is shielded, while the type of income that is already fairly tax-efficient sits where it does the least additional harm. The cumulative effect of this seemingly small structural choice, called "tax drag" when done poorly, can compound into a genuinely significant difference in a client\'s total after-tax wealth over a multi-decade investing horizon, even though the underlying INVESTMENTS (the actual securities held) are identical either way.',
          core: 'Asset location (WHICH type of account holds a given investment) is a distinct decision from asset allocation (WHICH asset classes to hold). Because different investment income types are taxed differently, placing tax-inefficient assets (like most bonds) in tax-advantaged accounts and tax-efficient assets (like many stocks) in taxable accounts can meaningfully reduce a client\'s total tax drag over time, without changing the underlying investment mix at all.',
          when: 'Any question about minimizing a client\'s tax burden without changing their actual asset allocation, or distinguishing "asset location" from "asset allocation."',
          formulas: ['Tax drag ≈ the reduction in a portfolio\'s effective after-tax return caused by taxes paid along the way, which compounds over a long time horizon.', 'General asset-location heuristic: place assets generating frequently-taxed, higher-taxed income (many bonds) in tax-advantaged accounts; place assets generating deferrable, often lower-taxed gains (many stocks) in taxable accounts — subject to each client\'s specific tax situation and jurisdiction.'],
          intuition: 'Asset location does not change WHAT a client owns, only WHERE (in which account "wrapper") each piece is held — like packing the exact same suitcase contents differently to avoid a fee charged specifically on certain item types, without changing what is actually being carried.',
          examples: [
            { level: 1, text: 'A client has both a taxable brokerage account and a tax-deferred retirement account, and wants an overall 60% stocks / 40% bonds allocation across the two combined. Without thinking about location, they simply hold 60/40 in EACH account separately. With location awareness, they could instead hold ALL the bonds in the tax-deferred account and ALL the stocks in the taxable account (assuming the account sizes allow it), reaching the same overall 60/40 mix across both accounts combined, while shielding the more frequently-taxed bond interest from annual taxation.' },
            { level: 2, text: 'Two identical clients each hold a $500,000 portfolio, 50% stocks / 50% bonds, over a 20-year horizon, with identical returns on each asset class. Client A ignores location and simply mirrors 50/50 in both a taxable and tax-deferred account. Client B locates the bonds in the tax-deferred account and stocks in the taxable account. Even though both clients own the exact same total dollar amount of stocks and bonds throughout, Client B is expected to end up with more after-tax wealth, because a larger share of the recurring, higher-taxed bond interest was shielded from annual taxation for those 20 years.' },
            { level: 3, text: 'A wealth manager explains asset location to a client who initially assumes it means "changing my investment mix to avoid taxes." What is the important correction to make? Asset location does NOT change what asset classes are held or in what overall proportion — the client\'s allocation stays fully aligned with their risk profile. It only changes WHICH ACCOUNT holds each piece of that same allocation. This distinction matters because a client should never be persuaded to take on a different amount of risk purely for tax reasons — the risk profile (from the suitability concepts) should drive the allocation; location is a separate, additional layer of efficiency applied ON TOP of an allocation that was already chosen for the right reasons.' }
          ],
          trap: 'Confusing "asset location" (which ACCOUNT holds an investment) with "asset allocation" (which ASSET CLASSES are held) — they are separate decisions, and tax efficiency should never be used to justify holding a materially different, less suitable risk profile than the client\'s circumstances call for.',
          checks: [
            { level: 1, q: '"Asset location" refers to:', options: ['Which asset classes a client holds', 'Which TYPE of account (taxable, tax-deferred, tax-exempt) holds a given investment', 'The geographic location of a client\'s adviser', 'The physical address on a brokerage statement'], a: 1, why: 'Location is specifically about the account "wrapper" an investment sits in, distinct from allocation (which asset classes are chosen).' },
            { level: 1, q: 'Can two clients hold identical investments but end up with different after-tax wealth?', options: ['No, this is impossible if the investments are identical', 'Yes — differences in which ACCOUNT TYPE holds each investment can meaningfully change the after-tax outcome, even with identical underlying holdings', 'Only if one client cheats on their taxes', 'Only if the two clients live in different countries'], a: 1, why: 'This is the entire point of asset location: the same investments, held in differently-taxed accounts, can produce different after-tax results.' },
            { level: 2, q: 'Which general heuristic is commonly used for tax-efficient asset location (subject to each client\'s specific situation)?', options: ['Always hold bonds in taxable accounts and stocks in tax-deferred accounts', 'Generally hold more tax-inefficient assets (like many bonds) in tax-advantaged accounts, and more tax-efficient assets (like many stocks) in taxable accounts', 'Location never matters — hold everything in whichever account is largest', 'Always hold 100% of every account in cash'], a: 1, why: 'Shielding the more frequently and heavily taxed income (typical bond interest) inside tax-advantaged accounts is the general heuristic, though it depends on the specific tax rules involved.' },
            { level: 2, q: 'Does optimizing asset location change a client\'s overall risk profile or asset allocation?', options: ['Yes, it always makes the portfolio more aggressive', 'No — done correctly, it changes only WHERE the same overall allocation is held, not WHAT that allocation is', 'Yes, it always makes the portfolio more conservative', 'Asset location and allocation are the same decision'], a: 1, why: 'A properly executed location strategy preserves the client\'s intended overall asset allocation across all their accounts combined.' },
            { level: 3, q: 'Why does "tax drag" compound into a larger effect over a multi-decade horizon than it might appear to be in any single year?', options: ['It does not compound at all — the effect is always small and constant', 'Because taxes paid each year reduce the amount available to keep growing in future years, and this effect accumulates and compounds over a long horizon', 'Tax drag only applies in the final year of investing', 'Tax rates always increase every year automatically'], a: 1, why: 'Money paid in taxes along the way is no longer available to compound further — over a long horizon this compounding difference can become substantial, even from a modest annual effect.' },
            { level: 3, q: 'A client wants to shift entirely into tax-exempt bonds, moving away from their suitable stock/bond mix, purely to reduce taxes. What is the appropriate response?', options: ['Agree immediately — minimizing taxes should always override the client\'s risk profile', 'Explain that tax efficiency should be optimized WITHIN a suitable allocation (e.g. via location), not used to justify abandoning the risk profile and allocation that actually fits the client\'s goals and capacity', 'Refuse to discuss taxes at all', 'Taxes are irrelevant to any wealth management conversation'], a: 1, why: 'Tax efficiency is a valuable additional layer, but it should never override the suitability-driven allocation decision covered in the earlier concepts.' }
          ]
        },
        {
          id: 'wmc2', name: 'Liquidity bucketing: matching WHEN money is needed to WHERE it is invested', track: 'wm',
          primer: '"Liquidity" describes how quickly and easily an asset can be converted into cash without a significant loss of value — cash itself is perfectly liquid; a publicly-traded stock is highly liquid (it can usually be sold within moments during market hours, close to its last traded price); real estate or a stake in a private equity fund is highly ILLIQUID (it can take months or years to sell, and a forced, urgent sale often has to accept a meaningfully lower price than a patient one would). A client\'s WEALTH is not one single, undifferentiated pool of money with one single time horizon — in reality, different portions of that wealth are earmarked, explicitly or implicitly, for different purposes arriving at very different points in time: near-term living expenses and an emergency reserve (needed essentially immediately, or on short notice), a mid-term goal like a house purchase or a child\'s university tuition (needed in a handful of years), and long-term goals like retirement decades away. "Liquidity bucketing" (sometimes called a "bucket strategy") is the practice of explicitly dividing a client\'s total wealth into separate buckets matched to these different time horizons, and investing EACH bucket differently, appropriate to how soon it will actually be needed — the near-term bucket held almost entirely in cash and highly liquid, low-volatility instruments (since this money cannot be allowed to be caught in a market downturn right when it is needed), the mid-term bucket in a moderate, partially liquid mix, and the long-term bucket invested more aggressively in less liquid, higher-expected-return assets, since it has decades to ride out volatility and does not need to be accessed on short notice. The core benefit of this structure is behavioral as much as financial: it gives a client concrete, tangible confidence that their near-term needs are secure and insulated from market swings, which in turn makes it psychologically far easier for them to stay invested in the higher-return, more volatile long-term bucket through periods of market stress, rather than panicking and selling everything (including money that was never actually needed soon) purely because a downturn is frightening in the moment.',
          core: 'Liquidity bucketing divides a client\'s wealth into separate pools matched to WHEN each portion will actually be needed — near-term needs held in cash/highly liquid instruments, longer-term needs invested more aggressively and less liquidly — both to structurally protect near-term needs from market swings and to make it psychologically easier to stay invested in the longer-term bucket during a downturn.',
          when: 'Any question about matching investment liquidity to a client\'s actual spending timeline, or about why a client should not invest emergency or near-term funds the same way as long-term retirement savings.',
          formulas: ['Liquidity of an asset ≈ how quickly it can be converted to cash without a meaningful loss of value relative to a patient sale.', 'General bucket structure: near-term bucket → cash/cash-equivalents; mid-term bucket → moderate, partially liquid mix; long-term bucket → growth-oriented, can tolerate illiquidity and volatility.'],
          intuition: 'Think of liquidity bucketing like packing for a trip with different bags for different needs: what you need to grab in the next five minutes goes in your pocket (cash), what you need this week goes in a carry-on (liquid, moderate holdings), and what you will not touch for years can be safely checked as luggage (less liquid, higher-growth holdings) — you would never want your passport (needed immediately) buried at the bottom of checked luggage (illiquid).',
          examples: [
            { level: 1, text: 'A client has $200,000 in total investable wealth. $20,000 is earmarked as an emergency reserve and near-term spending (needed within months). $180,000 is earmarked for retirement, 25 years away. A liquidity-bucketed approach would hold the $20,000 in cash or cash-equivalents (highly liquid, essentially no volatility) and could invest the $180,000 in a growth-oriented, more volatile mix, since it will not be touched for decades.' },
            { level: 2, text: 'A different client has $150,000 needed for a house down payment in 2 years, alongside $600,000 for retirement 30 years away. Even though the total investable wealth ($750,000) might tempt a one-size-fits-all allocation, the 2-year bucket should be invested very conservatively (a market downturn 18 months from now could derail the house purchase, with no time to recover), while the 30-year bucket has ample time to absorb volatility and can be invested far more aggressively.' },
            { level: 3, text: 'During a sharp market downturn, a client with a well-structured liquidity-bucket portfolio calls, worried about their investments. The adviser can point out that their near-term bucket (cash, needed for the next year of expenses) is completely unaffected by the market decline — it was never invested in anything volatile in the first place — and that only the long-term bucket, which was never going to be touched for decades regardless, has temporarily declined. This concrete, structural separation often provides real psychological reassurance that a single blended portfolio number cannot offer, making it easier for the client to avoid a panic-driven decision.' }
          ],
          trap: 'Investing near-term needs (an emergency fund, money needed within the next year or two) in the same volatile, growth-oriented mix as long-term retirement savings — a downturn arriving exactly when that near-term money is needed leaves no time to recover, unlike money with a genuinely long horizon.',
          checks: [
            { level: 1, q: 'An asset is "liquid" if:', options: ['It pays a high dividend', 'It can be quickly converted to cash without a significant loss of value', 'It is a type of bond', 'It has existed for a long time'], a: 1, why: 'Liquidity specifically describes ease and speed of conversion to cash without a meaningful value loss, distinct from risk, return, or asset type.' },
            { level: 1, q: 'Liquidity bucketing divides a client\'s wealth based primarily on:', options: ['The client\'s favorite investments', 'WHEN each portion of the wealth will actually be needed', 'The alphabetical order of the client\'s goals', 'Tax status only'], a: 1, why: 'Buckets are organized around time horizon/need for the funds, which then determines the appropriate liquidity and risk level for each bucket.' },
            { level: 2, q: 'Why should a near-term bucket (needed within months) be held mostly in cash rather than equities?', options: ['Cash always earns a higher return than equities', 'A market downturn right when the money is needed would leave no time to recover, unlike a long-horizon bucket', 'Equities cannot legally be held by wealth management clients', 'There is no real reason — cash and equities are interchangeable for any time horizon'], a: 1, why: 'The core risk being managed is a downturn occurring exactly when the funds must be accessed, with insufficient time to recover.' },
            { level: 2, q: 'A client needs $50,000 for a home renovation in 8 months and has $400,000 for retirement in 25 years. How should these two amounts generally be treated?', options: ['Identically, since they belong to the same client', 'Very differently — the $50,000 should be held very conservatively/liquid, the $400,000 can be invested more aggressively', 'Both should be invested 100% in equities', 'Both should be held entirely in cash'], a: 1, why: 'The dramatically different time horizons call for structurally different liquidity and risk treatment, even within the same client\'s total wealth.' },
            { level: 3, q: 'What is the PSYCHOLOGICAL (not just financial) benefit of liquidity bucketing during a market downturn?', options: ['There is no psychological benefit, only a financial one', 'Seeing that near-term needs are structurally protected from the downturn can make it easier for a client to stay invested in the long-term bucket rather than panic-selling', 'It guarantees the client will never feel anxious about anything', 'It eliminates the need for any client communication during downturns'], a: 1, why: 'Concrete, structural separation of near-term security from long-term growth exposure provides tangible reassurance that a single blended number often cannot.' },
            { level: 3, q: 'A client with a well-bucketed portfolio sees their TOTAL portfolio value fall during a downturn and wants to sell everything, including retirement funds not needed for 30 years. What is the most useful thing the adviser can point out?', options: ['That the entire portfolio should indeed be sold immediately', 'That the near-term bucket (their actual upcoming needs) is unaffected, and the declining portion is money that was never going to be touched for decades, giving ample time to recover', 'That liquidity bucketing has failed and should be abandoned', 'Nothing — there is no useful distinction to make'], a: 1, why: 'Reminding the client which portion of their wealth is actually at risk of being needed soon (none, in this case) directly addresses the source of their anxiety with concrete facts.' }
          ]
        }
      ]
    },

    /* =============================== WM-D =============================== */
    {
      unit: 'WM-D', topic: 'Alternative Investments (Client View)', title: 'Alternatives from the client\'s seat, not the fund manager\'s', track: 'wm', concepts: [
        {
          id: 'wmd1', name: 'Private equity, hedge funds and real assets: what a client is actually buying, and what it costs them', track: 'wm',
          primer: '"Alternative investments" is the umbrella term for asset classes that sit outside the traditional categories of publicly-traded stocks, bonds and cash — the three most common types a wealth management client might encounter are private equity (investing in companies that are NOT publicly traded on a stock exchange, typically held for many years before being sold), hedge funds (investment vehicles that pursue a wide range of strategies, often aiming to generate returns that are less tied to overall stock and bond market movements than a typical mutual fund), and real assets (physical, tangible holdings like real estate, infrastructure, or commodities). From a CLIENT\'s perspective — as opposed to the perspective of the fund manager actually running these vehicles — three practical characteristics matter most, and all three are meaningfully different from a typical publicly-traded stock or bond fund. First, ILLIQUIDITY: money committed to a private equity fund is typically locked up for many years (often 7-10+), with no ability to simply sell out early the way a client could sell a stock in seconds — in exchange for accepting this illiquidity, investors generally expect (though are never guaranteed) an extra return over time, called the "illiquidity premium," compensating them for giving up flexibility. Second, FEES: alternative investment vehicles typically charge meaningfully higher fees than traditional mutual funds or index funds — a very common structure, often called "two and twenty," charges roughly a 2% annual management fee on the total amount invested PLUS 20% of any investment profits generated, a fee load that can substantially erode net returns to the client if the underlying strategy does not significantly outperform its higher costs. Third, and often underappreciated, the ROLE alternatives are meant to play in an overall portfolio varies by type: some alternatives (many hedge fund strategies) are added specifically for DIVERSIFICATION — seeking returns less correlated with traditional stocks and bonds, potentially smoothing overall portfolio swings, even if their own expected return is not dramatically higher than public markets; others (much of private equity) are added specifically for return ENHANCEMENT, accepting illiquidity and higher risk in pursuit of higher expected long-run returns than public markets typically offer. A wealth manager evaluating whether alternatives are appropriate for a specific client must weigh all three factors together against that client\'s specific liquidity needs (from the earlier bucketing concept), fee sensitivity, and what role — diversification or return enhancement — the allocation is actually meant to serve.',
          core: 'Alternative investments (private equity, hedge funds, real assets) typically involve two client-relevant tradeoffs versus traditional public stocks/bonds: illiquidity (money locked up for years, in exchange for a potential "illiquidity premium") and higher fees (often structured as a percentage of assets plus a share of profits). Their INTENDED ROLE also varies — some are added for diversification, others specifically for return enhancement — and suitability depends on matching all of this to the client\'s actual liquidity needs and goals.',
          when: 'Any question about whether/how alternative investments fit into a client portfolio, or about the client-relevant tradeoffs (versus a fund manager\'s perspective) of illiquidity and fees.',
          formulas: ['A common alternative-investment fee structure: roughly 2% annual management fee on assets invested, plus roughly 20% of investment profits generated ("two and twenty") — though exact terms vary widely by fund and strategy.', 'Illiquidity premium (conceptual): the extra expected return investors generally seek as compensation for accepting a long, inflexible lock-up period, versus an equally risky but liquid alternative.'],
          intuition: 'A useful client-facing framing: money placed in an illiquid alternative investment is money that must genuinely be able to sit untouched for years — this is precisely why the liquidity-bucketing concept matters so much when deciding how much (if any) of a client\'s wealth is appropriate to commit to alternatives in the first place.',
          examples: [
            { level: 1, text: 'A client with $2m of investable wealth, of which $1.9m sits in their long-term retirement bucket (not needed for 25+ years) and $100,000 is their near-term emergency reserve, is considering a private equity fund with a 10-year lock-up. Only the long-term bucket is even a reasonable candidate for this allocation — committing any of the near-term emergency reserve to a 10-year lock-up would directly violate the liquidity-matching principle from the earlier concept, regardless of the fund\'s potential returns.' },
            { level: 2, text: 'A hedge fund charges a 2% management fee and 20% of profits. In a year where the fund returns 12% before fees, the client\'s NET return (before considering the management fee\'s effect on the base) is reduced by roughly 20% of that 12% gain (about 2.4 percentage points) for the performance fee, plus the separate 2% management fee — meaningfully eroding the gross return. This illustrates why the underlying strategy must meaningfully outperform (or provide meaningfully different, valuable diversification benefits) to justify a fee load this much higher than a typical low-cost index fund.' },
            { level: 3, text: 'A client asks: "should I add hedge funds to my portfolio to boost my returns?" A careful wealth manager would first clarify what ROLE the client is hoping alternatives will serve. If the goal is genuinely higher expected returns, many hedge fund strategies are not necessarily designed or expected to outperform public equities over the long run — some are explicitly designed to REDUCE volatility and provide diversification (lower correlation to stocks/bonds) rather than to maximize raw return. If the client\'s actual goal is diversification and smoother returns, that is a coherent, well-matched reason to consider certain hedge fund strategies; if the goal is purely to chase higher returns, a private equity allocation (which is more explicitly designed for return enhancement, at the cost of illiquidity) or simply a higher public-equity allocation might be more directly aligned with that specific goal.' }
          ],
          trap: 'Recommending an illiquid alternative investment without first confirming, via the liquidity-bucketing framework, that the client genuinely has funds available that will not be needed for the full lock-up period — and separately, assuming all alternative investments serve the same purpose (return enhancement), when many are specifically intended for diversification instead.',
          checks: [
            { level: 1, q: 'What is the "illiquidity premium" meant to compensate an investor for?', options: ['Paying higher management fees', 'Accepting a long lock-up period with no ability to easily sell early', 'Investing in publicly traded stocks', 'Choosing a low-fee index fund'], a: 1, why: 'Investors generally expect extra potential return as compensation specifically for giving up the flexibility to sell whenever they choose.' },
            { level: 1, q: 'A common alternative-investment fee structure, sometimes called "two and twenty," refers to:', options: ['2% of profits and 20% of assets', 'Roughly a 2% annual management fee on assets, plus roughly 20% of investment profits', 'A fund that only accepts investors for 2 to 20 years', 'A guaranteed 20% annual return with a 2% guarantee fee'], a: 1, why: 'This describes the fee structure itself (management fee + performance fee), not a return guarantee or investor eligibility window.' },
            { level: 2, q: 'Why should a client\'s near-term emergency reserve generally NOT be committed to a 10-year-lock-up private equity fund?', options: ['Private equity funds are illegal for individual clients', 'The lock-up directly conflicts with the near-term liquidity need — the money must remain accessible on short notice', 'Private equity always loses money', 'There is no conflict; any bucket is appropriate for any investment'], a: 1, why: 'This directly applies the liquidity-bucketing principle: committing near-term-needed funds to a long lock-up violates the basic matching of liquidity to time horizon.' },
            { level: 2, q: 'Do all types of alternative investments serve the same role in a portfolio?', options: ['Yes, they are all interchangeable and serve identical purposes', 'No — some are added primarily for diversification (less correlated returns), others primarily for return enhancement, and the client\'s goal should match the type chosen', 'Alternatives never have any specific role, they are just for show', 'Only hedge funds exist as a category of alternatives'], a: 1, why: 'Different alternative investment types are designed with different primary objectives, and matching the type to the client\'s actual goal matters.' },
            { level: 3, q: 'A client wants to reduce overall portfolio volatility through diversification, not necessarily maximize raw return. Which is the more directly aligned type of alternative to discuss?', options: ['A private equity fund explicitly focused on aggressive return enhancement', 'A hedge fund strategy specifically designed for lower correlation to traditional stocks and bonds', 'Any alternative investment works equally well for this specific goal', 'No alternative investment can ever help with diversification'], a: 1, why: 'Matching the INTENDED ROLE of the alternative (diversification versus return enhancement) to the client\'s actual stated goal is the key suitability judgment here.' },
            { level: 3, q: 'A hedge fund returns 12% gross in a year, charging 2% management fee and 20% of profits. Roughly how much of the gross gain is consumed by fees (management fee plus performance fee on the gain, order of magnitude)?', options: ['Roughly 0%, fees do not reduce client returns', 'A meaningful chunk — the 2% management fee plus roughly 20% of the 12% gain (about 2.4 percentage points) together erode a substantial part of the gross return', 'Exactly 50% of the gross return in every case', 'Fees only apply if the fund loses money'], a: 1, why: 'This order-of-magnitude estimate (2% + ~2.4% ≈ 4.4 percentage points of a 12% gross gain) illustrates why alternative investment fee loads meaningfully affect net client returns and must be weighed against expected benefits.' }
          ]
        }
      ]
    }
  ];

  global.QTL_LESSONS_WM = L;
})(window);
