/* QUANT TEST LAB — ASSET MANAGEMENT TRACK Learn content.
   Deliberately scoped to quantifiable content (factor exposure, fixed
   income, macro relationships) — no stock-pitch or open investment-case
   material, which needs a rubric engine this app does not have yet.
   Cross-references the existing quant-track Variance/Covariance/Portfolio
   Variance and Sharpe ratio concepts rather than repeating them. Same shape
   and depth standard as js/lessons.js (see concept 'c3' there for the
   reference bar). track:'am' on every unit. */
(function (global) {
  'use strict';

  const L = [

    /* =============================== AM-A =============================== */
    {
      unit: 'AM-A', topic: 'Factor Exposure', title: 'Decomposing returns into factors, and measuring skill relative to a benchmark', track: 'am', concepts: [
        {
          id: 'ama1', name: 'Factor models: splitting a return into "what the market gave you" and "what you actually added"',
          primer: 'A "factor" in asset management is a broad, systematic source of return that affects many securities at once, in a measurable, quantifiable way — the most basic and famous factor is simply the overall stock MARKET itself (when the whole market rises, most individual stocks tend to rise somewhat too), but there are many other well-documented factors, including "size" (smaller companies have historically shown different return patterns than larger ones) and "value" (statistically cheap companies, by certain financial ratios, have historically shown different return patterns than statistically expensive ones). A "factor exposure" (also called a "factor loading" or, for the market factor specifically, a "beta") is a number describing HOW SENSITIVE a particular security or portfolio is to a given factor\'s movements — a market beta of 1.2 means the security has tended to move about 20% MORE than the overall market, in the same direction; a market beta of 0.7 means it has tended to move about 30% LESS than the market. A "factor model" formally decomposes a security\'s (or portfolio\'s) total return into pieces: a separate contribution from EACH factor the security is exposed to (that factor\'s own return, scaled by the security\'s exposure/beta to it), plus one final leftover piece called "alpha," which captures whatever part of the return is NOT explained by any of the included factors at all. This decomposition matters enormously in practice because it lets an asset manager (and, just as importantly, the CLIENT evaluating that manager) separate two very different sources of investment return: return that came simply from being exposed to broad, systematic factors that were doing well anyway (which arguably required no special skill — anyone with the same factor exposures would have earned something similar) versus alpha, the residual return that the factor model could NOT explain, which is the part most plausibly attributable to genuine skill, unique insight, or a manager doing something the standard, well-known factors do not already capture.',
          core: 'Total return = alpha + Σ(factor exposure × that factor\'s own return). Factor exposures measure sensitivity to broad, systematic sources of return (like the overall market); alpha is the leftover return NOT explained by any included factor, and is the piece most plausibly attributable to genuine skill.',
          when: 'Any question asking you to decompose a return into factor-driven and unexplained (alpha) components, or to isolate how much of a manager\'s return came from skill versus broad market/factor exposure.',
          formulas: ['Total return = alpha + Σᵢ(factor exposureᵢ × factor returnᵢ).', 'Alpha = total return − Σᵢ(factor exposureᵢ × factor returnᵢ) — the residual, unexplained-by-factors piece.', 'Market beta specifically: a beta of b means the security has historically moved roughly b times as much as the market, in the same direction, for a given market move.'],
          intuition: 'Think of factor exposures as measuring how much of a portfolio\'s return is basically "riding along with" broad, well-known market forces (which anyone could access cheaply, e.g. via an index fund), while alpha measures the extra return actually attributable to the manager\'s own distinctive decisions, over and above that baseline.',
          examples: [
            { level: 1, text: 'A stock has alpha of 1%, a market beta of 1.1 on a market return of 8%, and no other factor exposures. Total return = 1% + (1.1×8%) = 1% + 8.8% = 9.8%.' },
            { level: 2, text: 'A portfolio returned 11% overall. It has a market beta of 1.0 on an 8% market return, and a size factor exposure of 0.4 on a 3% size factor return. Factor-explained return = (1.0×8%) + (0.4×3%) = 8% + 1.2% = 9.2%. Alpha = 11% − 9.2% = 1.8% — this 1.8% is the portion of the return not explained by exposure to the market or size factors.' },
            { level: 3, text: 'Two managers both returned 12% last year. Manager A has a market beta of 1.4 (an aggressive, high-beta approach) on an 8% market return, giving factor-explained return of 1.4×8% = 11.2%, and therefore alpha of just 12%−11.2% = 0.8%. Manager B has a market beta of 0.9 on the same 8% market, giving factor-explained return of 0.9×8% = 7.2%, and therefore alpha of 12%−7.2% = 4.8%. Despite identical TOTAL returns, Manager B generated far more alpha — Manager A\'s return is largely explained by simply taking on more market exposure than the market itself moved, which required comparatively little manager skill to achieve (a client could have replicated much of it with a leveraged index fund), while Manager B achieved the same total return with LESS market exposure, implying a meaningfully larger genuinely unexplained (skill-attributable) component.' }
          ],
          trap: 'Judging a manager purely by TOTAL return without decomposing how much of it came from factor exposure (which could often be replicated cheaply, e.g. via index funds) versus genuine alpha — a manager who simply took on more market risk than a client realized can look skilled on a total-return basis while having generated little or no actual alpha.',
          checks: [
            { level: 1, q: 'A security has a market beta of 1.3. What does this mean?', options: ['It has historically moved about 30% LESS than the market', 'It has historically moved about 30% MORE than the market, in the same direction', 'It always loses money when the market rises', 'Beta measures dividend yield, not sensitivity to the market'], a: 1, why: 'A beta above 1 means the security has tended to amplify market moves, moving further than the market in the same direction.' },
            { level: 1, q: '"Alpha" in a factor model refers to:', options: ['The total return of the portfolio', 'The portion of return NOT explained by any of the included factors', 'The market factor\'s own return', 'A synonym for beta'], a: 1, why: 'Alpha is specifically the residual, unexplained piece left over after accounting for all included factor exposures.' },
            { level: 2, q: 'A stock has alpha 0.5%, market beta 1.2 on an 7% market return, with no other factors. What is its total return?', options: ['7.5%', '8.9%', '8.4%', '7.7%'], a: 1, why: '0.5% + (1.2×7%) = 0.5% + 8.4% = 8.9%.' },
            { level: 2, q: 'A portfolio returns 10%, with factor-explained return of 6.5% from its market and value exposures combined. What is its alpha?', options: ['16.5%', '3.5%', '6.5%', '10%'], a: 1, why: 'Alpha = total return − factor-explained return = 10% − 6.5% = 3.5%.' },
            { level: 3, q: 'Two managers both return 9%. Manager X has market beta 1.5 on a 6% market (factor-explained = 9%, alpha = 0%). Manager Y has market beta 0.5 on the same 6% market (factor-explained = 3%, alpha = 6%). Which manager\'s return is more plausibly attributable to genuine skill?', options: ['Manager X, since beta is higher', 'Manager Y, since a much larger share of the identical total return is unexplained by market exposure alone', 'Both are identical since total returns match', 'Neither — total return is the only thing that matters'], a: 1, why: 'Despite identical total returns, Manager Y achieved it with far less market exposure, implying most of the return came from something other than simply riding the market — a much larger, more meaningful alpha.' },
            { level: 3, q: 'Why might comparing managers purely on TOTAL return be misleading?', options: ['Total return is always the single best and only measure needed', 'A high total return can be substantially explained by simply taking on more exposure to broad, cheaply-replicable factors, rather than reflecting genuine skill', 'Total return can never be measured accurately', 'Factor models are purely theoretical and have no practical relevance'], a: 1, why: 'Without decomposing return into factor-explained and alpha components, a client cannot distinguish genuine skill from simply taking on more of a broad, easily-accessible risk exposure.' }
          ]
        },
        {
          id: 'ama2', name: 'The information ratio: Sharpe ratio\'s sibling for measuring skill against a benchmark', track: 'am',
          primer: 'Recall from the quant track that the Sharpe ratio measures return earned per unit of TOTAL risk taken, comparing a portfolio\'s return to the RISK-FREE rate and dividing by the portfolio\'s own standard deviation. Many professional asset managers, however, are not actually trying to beat "cash" (the risk-free rate) — they are hired specifically to beat a particular BENCHMARK (a specific stock index, or a blend of indices) that represents the opportunity a client could access cheaply and passively on their own, without paying for active management at all. The "information ratio" is built on exactly the same logical structure as the Sharpe ratio, but swaps out both pieces to make this benchmark-relative comparison: instead of measuring return above the risk-free rate, it measures "active return" — the portfolio\'s return MINUS the benchmark\'s return (how much the manager beat or lagged the specific thing they were hired to outperform); and instead of dividing by the portfolio\'s own total volatility, it divides by "tracking error" — the standard deviation of that same return DIFFERENCE (portfolio minus benchmark) over time, which specifically measures how consistently, or how erratically, the manager\'s results have deviated from the benchmark, rather than measuring the portfolio\'s absolute up-and-down swings. A HIGH information ratio indicates that a manager has consistently beaten their benchmark by a meaningful amount relative to how much their results have bounced around that benchmark — exactly the risk-adjusted evidence of genuine, repeatable skill that a client evaluating an active manager (someone charging a fee specifically to try to beat a benchmark) actually needs, as opposed to simply looking at whether the manager beat the benchmark in any one single, possibly lucky, year.',
          core: 'Information ratio = (portfolio return − benchmark return) / tracking error, where tracking error is the standard deviation of the return difference (portfolio minus benchmark) over time. It plays the same structural role as the Sharpe ratio, but is specifically designed to evaluate an ACTIVE manager\'s skill against the benchmark they are actually hired to beat, rather than against the risk-free rate.',
          when: 'Any question comparing an active manager\'s return to their benchmark, or asking you to distinguish the information ratio from the Sharpe ratio.',
          formulas: ['Information ratio = (portfolio return − benchmark return) / tracking error.', 'Tracking error = standard deviation of (portfolio return − benchmark return), measured across multiple periods.', 'Contrast: Sharpe ratio = (portfolio return − risk-free rate) / portfolio standard deviation (a TOTAL-risk, risk-free-relative measure); information ratio = (portfolio return − benchmark return) / tracking error (a BENCHMARK-relative measure).'],
          intuition: 'The information ratio answers a very specific, practical client question: "for the fee I am paying this active manager to try to beat a specific benchmark, how much extra return am I getting per unit of the RISK OF DEVIATING from that benchmark, in either direction?" — a manager who reliably beats the benchmark by a small, steady amount can have a much better information ratio than one who occasionally beats it by a lot but is otherwise wildly inconsistent relative to it.',
          examples: [
            { level: 1, text: 'A portfolio returns 10% while its benchmark returns 8%, with a tracking error of 4%. Active return = 10%−8% = 2%. Information ratio = 2/4 = 0.5.' },
            { level: 2, text: 'Two managers both beat their benchmarks by 3% (active return of 3% each). Manager A has a tracking error of 2% (IR = 3/2 = 1.5); Manager B has a tracking error of 6% (IR = 3/6 = 0.5). Even though both managers achieved the exact same amount of outperformance, Manager A did so far more CONSISTENTLY relative to the benchmark (lower tracking error), earning a much better information ratio — Manager B\'s results likely swung much more erratically above and below the benchmark along the way, even if they landed at the same average outperformance.' },
            { level: 3, text: 'A manager achieves an information ratio of 0.6 with a tracking error of 5%. What was their active return? Rearranging the formula: active return = IR × tracking error = 0.6 × 5% = 3%. If their benchmark returned 9%, their own portfolio return must have been 9%+3% = 12%. This illustrates how the same formula can be worked in either direction, depending on which two of the three quantities (active return, tracking error, information ratio) are known.' }
          ],
          trap: 'Confusing the information ratio with the Sharpe ratio — they measure genuinely different things (benchmark-relative skill versus total-risk-adjusted return relative to cash) and use different denominators (tracking error versus total portfolio standard deviation); using the wrong one to evaluate an active manager\'s skill against their specific mandate can give a misleading picture.',
          checks: [
            { level: 1, q: 'The information ratio is structurally most similar to which other measure?', options: ['P/E ratio', 'The Sharpe ratio, but measured relative to a benchmark instead of the risk-free rate', 'Duration', 'Current yield'], a: 1, why: 'Both ratios divide an excess-return measure by a risk measure; the information ratio simply swaps the benchmark comparison for cash and tracking error for total volatility.' },
            { level: 1, q: 'What does "tracking error" measure?', options: ['The manager\'s total mistakes in a year', 'The standard deviation of the return difference between the portfolio and its benchmark over time', 'The portfolio\'s total volatility, ignoring the benchmark entirely', 'The benchmark\'s own volatility only'], a: 1, why: 'Tracking error specifically measures how consistently (or erratically) a portfolio\'s returns have deviated from its benchmark, not the portfolio\'s absolute volatility.' },
            { level: 2, q: 'A portfolio returns 13%, its benchmark returns 9%, and tracking error is 5%. What is the information ratio?', options: ['0.8', '1.8', '0.44', '4'], a: 0, why: 'Active return = 13−9 = 4%. IR = 4/5 = 0.8.' },
            { level: 2, q: 'Two managers both have an active return of 2%. Manager P has tracking error 1%; Manager Q has tracking error 4%. Which has the better information ratio?', options: ['Manager P (IR=2.0)', 'Manager Q (IR=0.5)', 'They are identical', 'Cannot be determined'], a: 0, why: 'Manager P: IR=2/1=2.0. Manager Q: IR=2/4=0.5. Lower tracking error for the same active return produces a higher, better information ratio.' },
            { level: 3, q: 'Why might using the SHARPE ratio instead of the information ratio give a misleading picture of an active manager\'s skill relative to their specific benchmark mandate?', options: ['They always give identical results, so it does not matter', 'The Sharpe ratio measures performance against the risk-free rate using total volatility, which does not isolate how well the manager did specifically against the benchmark they were hired to beat', 'The Sharpe ratio is only usable for bonds', 'The information ratio and Sharpe ratio use the same denominator'], a: 1, why: 'A manager could have a strong Sharpe ratio simply from broad market exposure while adding little value relative to their specific benchmark — the information ratio isolates that benchmark-specific skill instead.' },
            { level: 3, q: 'A manager has an information ratio of 0.75 and a tracking error of 4%. If the benchmark returned 7%, what was the manager\'s own portfolio return?', options: ['10%', '3%', '7.75%', '4.75%'], a: 0, why: 'Active return = IR × TE = 0.75×4% = 3%. Portfolio return = benchmark + active return = 7%+3% = 10%.' }
          ]
        }
      ]
    },

    /* =============================== AM-B =============================== */
    {
      unit: 'AM-B', topic: 'Fixed Income', title: 'Duration, convexity, and building a bond portfolio to a target', track: 'am', concepts: [
        {
          id: 'amb1', name: 'Convexity: the correction that duration alone gets wrong for big yield moves', track: 'am',
          primer: 'Recall that "modified duration" gives a first-order (straight-line) approximation of how much a bond\'s price changes for a given change in yield: ΔP/P ≈ −(modified duration)×Δy. This approximation works reasonably well for SMALL yield changes, but the TRUE relationship between a bond\'s price and its yield is not actually a straight line at all — it is a smooth CURVE, and specifically, that curve is shaped so that bond prices rise MORE when yields fall than they lose when yields rise by the same amount, an asymmetry that a simple straight-line (duration-only) approximation completely misses. "Convexity" is the mathematical measure of exactly how CURVED this true price-yield relationship is — technically, it captures the RATE OF CHANGE of duration itself as yields move, which is why it improves on the plain duration approximation specifically for LARGER yield moves, where the straight-line approximation\'s error becomes most noticeable. The improved, second-order approximation adds a convexity term on top of the duration term: ΔP/P ≈ −(modified duration × Δy) + ½×(convexity)×(Δy)². Two crucial features of this convexity term are worth noticing directly. First, the yield change is SQUARED, which means the convexity adjustment is always the SAME SIGN (positive, assuming positive/ordinary convexity) regardless of whether yields rose or fell — this precisely captures the asymmetry described above: convexity always helps a bond\'s actual price outcome relative to what the plain duration estimate alone would predict, whether yields moved up or down. Second, because the yield change is squared, the convexity term grows much faster than the duration term as the yield move gets larger, which is exactly why convexity barely matters for tiny yield moves but becomes increasingly important for larger ones. All else equal, a bond with HIGHER convexity is more attractive to hold, because it benefits more from favorable yield moves and is cushioned more against unfavorable ones, compared to a lower-convexity bond with the identical duration.',
          core: 'Convexity corrects for the curvature that a straight-line duration estimate misses: ΔP/P ≈ −(duration×Δy) + ½×convexity×(Δy)². Because the yield-change term is squared, the convexity adjustment is always favorable (in the same direction) regardless of whether yields rose or fell, and it matters increasingly for larger yield moves. Higher convexity, at the same duration, is generally more attractive to a bondholder.',
          when: 'Any question about bond price sensitivity for a LARGE yield move, or about why duration alone becomes a less accurate approximation as the yield change grows.',
          formulas: ['Second-order (duration + convexity) approximation: ΔP/P ≈ −(modified duration × Δy) + ½ × convexity × (Δy)².', 'The convexity term is always non-negative for ordinary (positively convex) bonds, since it depends on (Δy)², regardless of the sign of Δy.'],
          intuition: 'Picture the true price-yield relationship as a gentle smile-shaped curve rather than a straight line — a straight-line (duration-only) approximation, drawn tangent to that curve at the starting yield, will always underestimate the TRUE price for both yield increases and yield decreases, because the actual curve bows away from the straight line in the favorable direction on both sides.',
          examples: [
            { level: 1, text: 'A bond has modified duration 6 and convexity 50. Yields fall by 100bps (Δy = −0.01). Duration-only estimate: ΔP/P ≈ −6×(−0.01) = +6%. Adding convexity: convexity term = ½×50×(−0.01)² = ½×50×0.0001 = 0.0025 = +0.25%. Total ≈ 6%+0.25% = 6.25% — the true price gain is a bit LARGER than the duration-only estimate suggested.' },
            { level: 2, text: 'The same bond (duration 6, convexity 50), but now yields RISE by 100bps (Δy = +0.01). Duration-only estimate: ΔP/P ≈ −6×0.01 = −6%. Convexity term = ½×50×(0.01)² = +0.25% (the same positive value as before, since the yield change is squared). Total ≈ −6%+0.25% = −5.75% — the true price LOSS is a bit SMALLER than the duration-only estimate suggested. Notice the convexity term helped the bondholder in BOTH directions: a bigger gain when yields fell, and a smaller loss when yields rose.' },
            { level: 3, text: 'Two bonds have the identical modified duration of 7, but Bond A has convexity 30 and Bond B has convexity 90. For a large 150bp yield move in either direction, which bond would an investor generally prefer to hold, all else (like yield) being equal? Bond B, with the higher convexity, since its second-order term (½×90×Δy²) is larger than Bond A\'s (½×30×Δy²) — meaning Bond B\'s actual price response is cushioned MORE against an adverse yield move and boosted MORE by a favorable one, relative to what the shared duration-only estimate alone would suggest for both bonds.' }
          ],
          trap: 'Applying only the duration term for a LARGE yield move and ignoring convexity entirely — the resulting error grows quickly (since the omitted convexity term scales with the SQUARE of the yield change), making the duration-only estimate meaningfully inaccurate exactly when the yield move is big enough to matter most.',
          checks: [
            { level: 1, q: 'Why does duration ALONE become a less accurate approximation for LARGE yield changes?', options: ['Duration is always perfectly accurate regardless of the size of the yield move', 'The true price-yield relationship is curved, not a straight line, and duration only captures the straight-line (first-order) approximation', 'Large yield changes make duration undefined', 'Convexity only exists for very small yield changes'], a: 1, why: 'Duration is a linear (first-order) approximation to what is actually a curved relationship; the approximation error grows as the yield move gets larger.' },
            { level: 1, q: 'In the second-order approximation, why is the yield change SQUARED in the convexity term?', options: ['It is a typo and should not be squared', 'Squaring makes the convexity adjustment the same (favorable) sign regardless of whether yields rose or fell, capturing the curve\'s asymmetric benefit in both directions', 'Squaring is used purely for decorative mathematical reasons with no real meaning', 'It only applies when yields fall, not when they rise'], a: 1, why: 'Since (Δy)² is always non-negative, the convexity term is always additive/favorable, whether the yield move was up or down.' },
            { level: 2, q: 'A bond has duration 5 and convexity 40. Yields fall by 80bps. What is the convexity term\'s contribution alone (½×convexity×Δy²), in percent?', options: ['0.128%', '1.28%', '0.0128%', '3.2%'], a: 0, why: '½×40×(0.008)² = 20×0.000064 = 0.00128 = 0.128%.' },
            { level: 2, q: 'Using the SAME bond (duration 5, convexity 40) with yields RISING by 80bps instead, is the convexity term\'s contribution positive or negative?', options: ['Negative, since yields rose', 'Still positive — the same +0.128%, since (Δy)² does not depend on the sign of Δy', 'Exactly zero', 'It depends on the coupon rate'], a: 1, why: 'Because the yield change is squared, the convexity contribution has the same sign (positive, for ordinary convexity) regardless of whether yields rose or fell.' },
            { level: 3, q: 'All else (including duration) being equal, why would a bond investor generally prefer HIGHER convexity?', options: ['Higher convexity always means a higher coupon rate', 'A higher-convexity bond benefits more from favorable yield moves and is cushioned more against unfavorable ones, for the same duration', 'Convexity has no effect on an investor\'s actual outcomes', 'Higher convexity always means lower duration'], a: 1, why: 'The convexity term adds a favorable adjustment in both directions, and a larger convexity value means a larger favorable adjustment.' },
            { level: 3, q: 'A bond has duration 6, convexity 70, and yields rise by 120bps. What is the total (duration + convexity) approximate percentage price change?', options: ['−6.696%', '−7.2%', '−7.704%', '−6.2%'], a: 0, why: 'Duration term = −6×0.012 = −7.2%. Convexity term = ½×70×(0.012)² = 35×0.000144 = 0.00504 = +0.504%. Total ≈ −7.2%+0.504% = −6.696%.' }
          ]
        }
      ]
    },

    /* =============================== AM-C =============================== */
    {
      unit: 'AM-C', topic: 'Macro', title: 'Quantifiable macro relationships every allocator uses', track: 'am', concepts: [
        {
          id: 'amc1', name: 'Real versus nominal rates, and what the yield curve\'s shape is telling you', track: 'am',
          primer: 'The "nominal" interest rate is the rate actually stated on a loan, bond, or savings account — the plain number quoted in the market. The "real" interest rate strips out the effect of inflation, measuring the actual growth in PURCHASING POWER an investor earns, after accounting for the fact that prices for goods and services are generally rising over time too. The (approximate) "Fisher relationship" connects the two in the simplest, most commonly used form: real rate ≈ nominal rate − expected inflation rate — meaning that if inflation is running hot, a seemingly attractive nominal interest rate might actually represent very little (or even negative) REAL growth in purchasing power once inflation\'s erosion is accounted for. This distinction matters enormously for asset allocation: an investor evaluating whether bonds, cash, or other assets offer an attractive return should generally be thinking in REAL terms, not just nominal terms, since it is real purchasing power that ultimately funds real future spending. Separately, the "yield curve" plots government bond yields across different maturities (like 2-year, 10-year, 30-year), and its SHAPE carries widely-watched macroeconomic information. A "normal" (upward-sloping) curve, where longer-maturity yields exceed shorter-maturity yields, is the typical, historically most common shape — investors generally demand extra compensation for locking up money for longer, all else equal. An "inverted" curve, where SHORTER-maturity yields exceed longer-maturity ones, is a comparatively unusual and closely-watched shape, historically associated (though never guaranteed as a certainty) with markets expecting future interest rate cuts, and has often preceded economic slowdowns — though the specific relationship, and how reliably it predicts anything, is genuinely debated among economists. The "term spread" (long-maturity yield minus short-maturity yield) is simply the single number used to summarize and track this curve shape over time: positive means normal/upward-sloping, negative means inverted, and close to zero means flat.',
          core: 'Real rate ≈ nominal rate − expected inflation (the approximate Fisher relationship) — what matters for actual purchasing power. The yield curve\'s shape (summarized by the term spread = long yield − short yield) is closely watched: positive/normal is typical, negative/inverted is unusual and has historically often preceded economic slowdowns, though this relationship is not a certainty.',
          when: 'Any question converting between nominal and real interest rates, or interpreting the shape/spread of a yield curve.',
          formulas: ['Approximate Fisher relationship: real rate ≈ nominal rate − expected inflation rate (and equivalently, nominal rate ≈ real rate + expected inflation rate).', 'Term spread = long-maturity yield − short-maturity yield. Positive ⇒ normal/upward-sloping curve; negative ⇒ inverted curve; near zero ⇒ flat curve.'],
          intuition: 'The nominal rate tells you how many MORE dollars you will have; the real rate tells you how much MORE you can actually BUY with them — a high nominal rate during a period of even higher inflation can still leave an investor worse off in real, purchasing-power terms.',
          examples: [
            { level: 1, text: 'The nominal rate is 6% and expected inflation is 4%. Real rate ≈ 6%−4% = 2% — the investor\'s purchasing power grows by only about 2% per year, despite the seemingly attractive 6% nominal figure.' },
            { level: 2, text: 'The 2-year yield is 4.5% and the 10-year yield is 4.0%. Term spread = 4.0%−4.5% = −0.5 percentage points — a NEGATIVE spread, meaning the curve is inverted (the shorter maturity actually yields MORE than the longer maturity here).' },
            { level: 3, text: 'An investor is deciding between a bond yielding a nominal 7% (with inflation expected at 5%, giving a real rate of about 2%) and an alternative asset expected to return a nominal 5% (with the SAME 5% inflation expectation, giving a real return of about 0%). Purely on a real, purchasing-power basis, the 7% nominal bond is meaningfully more attractive (≈2% real) than the 5% nominal alternative (≈0% real) — this illustrates why simply comparing nominal figures across two choices with different embedded inflation exposure can be misleading; what ultimately matters is the REAL return each one is expected to deliver.' }
          ],
          trap: 'Comparing two nominal rates directly without accounting for inflation, or assuming a high nominal rate automatically means an attractive REAL return — a high nominal rate paired with even higher inflation can actually represent negative real purchasing-power growth.',
          checks: [
            { level: 1, q: 'The real interest rate measures:', options: ['The rate exactly as stated/quoted in the market', 'Growth in actual purchasing power, after removing the effect of inflation', 'A synonym for the nominal rate', 'Only the rate on government bonds'], a: 1, why: 'Real rates strip out inflation\'s erosion to reflect true purchasing-power growth.' },
            { level: 1, q: 'The approximate Fisher relationship states:', options: ['Real rate ≈ nominal rate + inflation', 'Real rate ≈ nominal rate − inflation', 'Nominal rate ≈ inflation ÷ real rate', 'Real and nominal rates are always identical'], a: 1, why: 'The simple approximation subtracts expected inflation from the nominal rate to estimate the real rate.' },
            { level: 2, q: 'Nominal rate is 8%, expected inflation is 3%. What is the approximate real rate?', options: ['11%', '5%', '3%', '2.67%'], a: 1, why: '8% − 3% = 5%.' },
            { level: 2, q: 'The 2-year yield is 3% and the 10-year yield is 4.5%. What is the term spread, and what curve shape does it indicate?', options: ['−1.5 points, inverted', '+1.5 points, normal (upward-sloping)', '+7.5 points, flat', '0 points, flat'], a: 1, why: 'Spread = 4.5%−3% = +1.5 points; positive spread indicates a normal, upward-sloping curve.' },
            { level: 3, q: 'What has an inverted yield curve historically often been associated with (though not guaranteed as a certainty)?', options: ['A period of unusually stable, low-volatility growth with no other implications', 'Markets expecting future interest rate cuts, and it has often preceded economic slowdowns', 'It has no historical association with anything macroeconomic', 'Guaranteed hyperinflation within one year'], a: 1, why: 'This is a well-documented historical pattern, though the exact reliability and mechanism are genuinely debated among economists — it is not a certainty.' },
            { level: 3, q: 'An investor compares Bond X (nominal 6%, expected inflation environment 5%) to Bond Y (nominal 4%, expected inflation environment 1%). Which offers the better approximate REAL return?', options: ['Bond X (real ≈1%)', 'Bond Y (real ≈3%)', 'They are identical in real terms', 'Real return cannot be estimated from this information'], a: 1, why: 'Bond X: 6%−5% ≈ 1% real. Bond Y: 4%−1% ≈ 3% real. Despite Bond X\'s HIGHER nominal rate, Bond Y offers the better real, purchasing-power return — illustrating why nominal comparisons alone can mislead.' }
          ]
        }
      ]
    }
  ];

  global.QTL_LESSONS_AM = L;
})(window);
