/* QUANT TEST LAB — INVESTMENT BANKING TRACK Learn content.
   Same shape and depth standard as js/lessons.js (see concept 'c3' there for
   the reference bar). For finance concepts specifically, every primer goes
   beyond the formula: where the number comes from, what it means in
   practice, and what a high vs. low result implies for a company's health,
   risk or value — not just "how to compute it." track:'ib' on every unit. */
(function (global) {
  'use strict';

  const L = [

    /* =============================== IB-A =============================== */
    {
      unit: 'IB-A', topic: 'Accounting Flows', title: 'How a transaction moves through the three financial statements', track: 'ib', concepts: [
        {
          id: 'iba1', name: 'The three statements, and why one transaction touches all of them',
          primer: 'Before anything else, three terms need defining precisely, because interview and assessment questions live and die on confusing them. The "income statement" (also called the P&L, for "profit and loss") reports a company\'s revenue, its costs, and the profit left over, for a specific PERIOD of time (like a quarter or a year) — it answers "how much did the company earn during this period, on paper?" The "cash flow statement" reports how much actual CASH moved into and out of the company during that same period, split into three sections (operating, investing, financing) — it answers "how much real money changed hands?" and critically, it can differ substantially from the income statement, because accounting profit and cash are NOT the same thing (a sale can be recorded as revenue before the customer actually pays, for instance). The "balance sheet" is different in kind from the other two: instead of covering a period, it is a snapshot at one single INSTANT — it lists everything the company owns (assets), everything it owes (liabilities), and the difference between them (equity), always obeying the identity Assets = Liabilities + Equity at every single moment. The reason these three statements are always taught and tested TOGETHER, rather than separately, is that they are not independent — every single transaction a company makes shows up in more than one of them SIMULTANEOUSLY, because of how accounting is built: the income statement\'s bottom line (net income) flows directly into both the cash flow statement (as its starting point) and the balance sheet (added into retained earnings, part of equity); the cash flow statement\'s bottom line (the net change in cash) flows directly into the balance sheet\'s cash line. This is why the classic interview drill of "walk me through how a $10 depreciation charge affects all three statements" is really testing whether you understand this WIRING between the statements, not just one isolated formula.',
          core: 'The income statement asks "how much did we earn this period," the cash flow statement asks "how much cash actually moved," and the balance sheet is a snapshot of everything owned versus owed at one instant. They are wired together: net income flows into both cash flow and retained earnings; the cash flow statement\'s ending cash flows into the balance sheet.',
          when: 'Any "how does this transaction flow through the financials" question, or any question asking you to reconcile net income with cash flow or a balance sheet change.',
          formulas: ['Balance sheet identity, true at every instant: Assets = Liabilities + Equity.', 'Net income (from the income statement) is the starting line of the cash flow statement.', 'Ending cash (from the cash flow statement) becomes the cash balance on the next balance sheet; net income (net of dividends) flows into retained earnings, part of equity.'],
          intuition: 'Think of the income statement and cash flow statement as two different LENSES on the same underlying events — one measures economic performance on an accrual basis (was value created?), the other measures pure cash movement (did money actually move?) — and the balance sheet is the running scoreboard that both lenses ultimately feed into.',
          examples: [
            { level: 1, text: 'A company makes a $100 cash sale, with $60 of cost of goods sold. Income statement: revenue +$100, cost −$60, so net income +$40 (ignoring tax for simplicity). Cash flow statement: since the sale was for cash, operating cash flow also increases, ultimately by $40 net (mirroring net income when there is no working-capital timing difference). Balance sheet: cash goes up by $40 (net effect after paying for the goods), and retained earnings (inside equity) goes up by $40, keeping Assets = Liabilities + Equity balanced.' },
            { level: 2, text: 'A company makes a $100 sale ON CREDIT (the customer has not paid yet), with $60 of cost. Income statement: still shows revenue +$100, net income +$40 immediately — accounting recognises revenue when it is EARNED, not when cash is received. Cash flow statement: net income of +$40 flows in, but an increase in accounts receivable of $100 is subtracted (money is owed but not yet collected), giving operating cash flow of 40−100 = −$60 net cash effect from this sale alone (assuming the $60 cost was paid in cash). Balance sheet: accounts receivable (an asset) rises by $100, cash falls by $60 (from paying the cost), and retained earnings rises by $40 — check: ΔAssets = +100−60 = +40, which equals ΔEquity = +40. Balanced.' },
            { level: 3, text: 'A company takes out a $200 bank loan. Income statement: NO effect at all — borrowing money is not revenue and creates no profit or loss. Cash flow statement: +$200 appears in the FINANCING section (not operating), since this is raising capital, not running the business. Balance sheet: cash (an asset) rises by $200, and debt (a liability) also rises by $200 — Assets and Liabilities move together by the same amount, so equity is completely unaffected, and the identity still balances (ΔAssets=+200=ΔLiabilities+ΔEquity(0)).' }
          ],
          trap: 'Assuming net income and cash flow must always be equal — they are usually different by design, precisely because of non-cash items (like depreciation) and timing differences (like a sale made on credit, or a cost paid in advance). A profitable company reporting positive net income can still run out of CASH if too much of its "profit" is trapped in unpaid receivables.',
          checks: [
            { level: 1, q: 'Which statement is a SNAPSHOT at one instant, rather than covering a period of time?', options: ['Income statement', 'Cash flow statement', 'Balance sheet', 'All three cover a period'], a: 2, why: 'The balance sheet reports assets, liabilities and equity as they stand at one specific moment; the other two statements cover a period.' },
            { level: 1, q: 'What is the balance sheet identity that must hold at every instant?', options: ['Revenue = Costs + Profit', 'Assets = Liabilities + Equity', 'Cash In = Cash Out', 'Net Income = Cash Flow'], a: 1, why: 'Everything a company owns (assets) is financed either by what it owes (liabilities) or by the owners\' stake (equity).' },
            { level: 2, q: 'A company makes a $50 sale entirely on credit (no cash received yet), with no costs. What happens on the balance sheet?', options: ['Cash rises by $50', 'Accounts receivable rises by $50, and retained earnings rises by $50', 'Nothing changes until the cash is collected', 'Liabilities rise by $50'], a: 1, why: 'Revenue is recognised immediately (raising retained earnings via net income), but since no cash was received, the offsetting asset is accounts receivable, not cash.' },
            { level: 2, q: 'A company takes out a loan. What is the effect on net income?', options: ['Net income rises by the loan amount', 'Net income falls by the loan amount', 'No effect at all', 'It depends on the interest rate'], a: 2, why: 'Borrowing money is a financing activity, not revenue or an expense — it has zero direct effect on the income statement (only the resulting interest expense, in future periods, would).' },
            { level: 3, q: 'Why can a profitable company (positive net income) still run out of cash?', options: ['This is impossible if net income is positive', 'Because "profit" and "cash" measure different things — profit can be tied up in unpaid receivables or inventory rather than converted to cash', 'Because taxes are always paid in cash', 'Because the balance sheet identity would be violated otherwise'], a: 1, why: 'Net income is an accrual concept; if too much revenue sits uncollected as receivables, or cash is tied up building inventory, a "profitable" company can still be cash-starved.' },
            { level: 3, q: 'A company pays $30 cash for a cost that was already recorded as an expense last quarter (an accrued liability being settled). What happens THIS quarter?', options: ['Net income falls by $30 this quarter', 'No income statement effect this quarter; cash falls by $30 and the liability (accrued expense) falls by $30', 'Revenue falls by $30', 'Nothing happens on any statement'], a: 1, why: 'The expense already hit the income statement when it was ACCRUED (recognised); paying it later is a pure cash/liability event with no NEW income statement impact — this is the mirror image of the credit-sale example.' }
          ]
        },
        {
          id: 'iba2', name: 'Depreciation and the tax shield: why "non-cash" does not mean "irrelevant to cash"',
          primer: 'When a company buys a long-lived physical asset — a factory, a machine, a fleet of trucks — accounting rules do not let it record the entire purchase price as an expense in the year of purchase, because that would make the income statement misleading (a single huge expense in year one, then nothing in the many years the asset is actually used to generate revenue). Instead, the purchase cost is spread out over the asset\'s useful life as a series of smaller annual charges called "depreciation," each of which reduces reported profit a little at a time, matching the expense to the years the asset actually helps produce revenue — this accounting technique is called the "matching principle." The single most important, most frequently tested fact about depreciation is that it is a "non-cash" expense: the actual CASH for the asset was already paid out, in full, back when it was originally purchased (as an investing activity), so recording MORE depreciation charges in later years does not cause any FURTHER cash to leave the company at that time — the cash impact already happened. So what is depreciation\'s real effect on cash, if any? It comes entirely through taxes: because tax authorities allow depreciation to be deducted from taxable income (just like any other expense), a company that records more depreciation reports lower taxable profit, and therefore pays LESS in actual cash taxes than it would if depreciation were zero — this saving is called the "depreciation tax shield," and it equals the depreciation charge multiplied by the tax rate. This is precisely why, when building a cash flow statement from net income, accountants first SUBTRACT depreciation as an expense to get net income (following normal accounting rules), and then ADD IT BACK when computing cash flow — the add-back cancels out the artificial reduction to net income, but the reduced TAX BILL (which was genuinely paid in cash, calculated using the lower, depreciation-reduced taxable income) remains as a real cash benefit.',
          core: 'Depreciation itself moves no cash (the cash left when the asset was bought). Its only real cash effect is the "tax shield": by lowering taxable income, it lowers the actual cash tax bill by (depreciation × tax rate). On the cash flow statement, depreciation is added back to net income precisely to cancel out its artificial, non-cash reduction to reported profit.',
          when: 'Any "how does depreciation/amortisation affect net income, cash flow, or the balance sheet" question, and any DCF or LBO model where you must add back D&A to get from net income to cash flow.',
          formulas: ['Net income impact of a depreciation charge D at tax rate t = −D × (1 − t).', 'Cash flow impact of that same depreciation charge = +D × t (the tax shield only).', 'Cash flow build-up: Cash flow from operations = Net income + Depreciation & amortisation (add-back) + other non-cash items ± working-capital changes.'],
          intuition: 'A useful gut-check: if a $100 machine purchase is spread over 10 years as $10/year of depreciation, the $100 in CASH left the building the day the machine was bought — recording "$10 of depreciation" in year 5 is bookkeeping, not a fresh $10 leaving the bank account; only the resulting tax saving in year 5 is genuinely new cash.',
          examples: [
            { level: 1, text: 'A company has $200 of pre-tax income before depreciation, then records $50 of depreciation, at a 25% tax rate. Taxable income = 200−50 = $150. Tax = 150×25% = $37.50. Net income = 150−37.50 = $112.50. Now compare to a hypothetical with ZERO depreciation: taxable income = $200, tax = $50, net income = $150. The depreciation REDUCED net income by 150−112.50 = $37.50, which is exactly $50×(1−25%) = $37.50, matching the formula.' },
            { level: 2, text: 'Using the same numbers, what is the cash flow effect of that depreciation, versus the zero-depreciation scenario? With depreciation: cash tax paid = $37.50. Without depreciation: cash tax paid = $50. The company with depreciation pays $50−37.50 = $12.50 LESS in cash taxes — exactly the tax shield, $50×25% = $12.50. On the cash flow statement directly: net income of $112.50, plus the $50 depreciation add-back, gives operating cash flow of $162.50 — compare this to the no-depreciation net income of $150 (which, with no non-cash addback needed, is also its cash flow): $162.50 vs $150 is a $12.50 cash ADVANTAGE from having the depreciation deduction, confirming the tax shield once again.' },
            { level: 3, text: 'A company\'s net PP&E (property, plant & equipment) was $500 at the start of the year. During the year it spent $80 on capital expenditures (buying new equipment) and recorded $60 of depreciation. What is net PP&E at year end, and does this affect cash directly? Net PP&E rolls forward as: starting balance + capex − depreciation = 500+80−60 = $520. The capex of $80 is a genuine NEW cash outflow this year (shown in the investing section of the cash flow statement); the $60 of depreciation, being a reduction of an asset ALREADY paid for, causes no new direct cash outflow — its only cash effect is, again, the tax shield on the income statement side.' }
          ],
          trap: 'Treating depreciation as if it reduces cash flow by its full amount, the same way it reduces net income — this conflates a non-cash accounting charge with an actual cash expense. The correct cash effect of depreciation is ONLY the tax shield (depreciation × tax rate), and it is a cash BENEFIT (it lowers the tax bill), not a cash cost.',
          checks: [
            { level: 1, q: 'Depreciation is described as a "non-cash" expense because:', options: ['It never appears on any financial statement', 'The cash for the underlying asset was already spent when it was purchased; the depreciation charge itself moves no new cash', 'Depreciation is illegal to deduct from taxes', 'It only appears on the balance sheet'], a: 1, why: 'The cash outflow happened at the original purchase (an investing activity); the subsequent depreciation charges are a bookkeeping allocation of that already-spent cash, not new cash leaving the company.' },
            { level: 1, q: 'On the cash flow statement, depreciation is:', options: ['Subtracted from net income', 'Added back to net income', 'Ignored entirely', 'Multiplied by the tax rate before being used at all'], a: 1, why: 'Since depreciation already reduced net income under normal accounting rules but involves no new cash, it is added back to reconstruct the actual cash flow.' },
            { level: 2, q: 'A $40 depreciation charge at a 30% tax rate. What is the net income impact?', options: ['−$40', '−$12', '−$28', '+$12'], a: 2, why: 'Net income impact = −D×(1−t) = −40×0.7 = −$28.' },
            { level: 2, q: 'Using the same $40 depreciation charge at a 30% tax rate, what is the CASH FLOW impact?', options: ['−$40', '+$12', '−$28', '$0'], a: 1, why: 'Cash flow impact = the tax shield only = D×t = 40×0.3 = +$12 (a cash benefit from the lower tax bill).' },
            { level: 3, q: 'Why does a company prefer MORE depreciation deductions (all else equal), from a pure cash perspective?', options: ['It has no cash effect either way', 'More depreciation lowers taxable income, which lowers the actual cash taxes paid — a genuine cash benefit via the tax shield', 'It increases reported net income', 'It has nothing to do with taxes'], a: 1, why: 'Even though higher depreciation lowers reported net income, its tax-shield effect is a real cash inflow (relative to lower depreciation), which is why accelerated depreciation methods are often used for tax purposes.' },
            { level: 3, q: 'Net PP&E starts the year at $300. The company spends $40 on capex and records $25 of depreciation. What is ending net PP&E, and which of those two numbers is a genuinely NEW cash outflow this year?', options: ['$315 ending; the $25 depreciation is the new cash outflow', '$315 ending; the $40 capex is the new cash outflow', '$265 ending; neither is a cash outflow', '$340 ending; both are cash outflows of equal size'], a: 1, why: 'Ending PP&E = 300+40−25 = $315. Capex is a fresh cash outflow (investing activity) this year; depreciation merely allocates a PAST cash outflow and creates no new direct cash movement.' }
          ]
        }
      ]
    },

    /* =============================== IB-B =============================== */
    {
      unit: 'IB-B', topic: 'DCF Valuation', title: 'Discounted cash flow: WACC, terminal value, and what the number means', track: 'ib', concepts: [
        {
          id: 'ibb1', name: 'The discount rate: why future cash is worth less, and how WACC blends the cost of two different funding sources',
          primer: 'A discounted cash flow (DCF) valuation is built on one core idea: a dollar promised to you a year from now is worth LESS than a dollar in your hand today, because (a) you could invest today\'s dollar and have MORE than a dollar by next year, and (b) a future promise carries risk that it might not actually arrive. "Discounting" is the mathematical process of converting a future cash amount into its equivalent value today, by dividing it by (1 + discount rate) raised to the power of how many years away it is — the discount rate itself represents the annual return an investor could reasonably expect from an alternative investment of similar risk, so a HIGHER discount rate means future cash is treated as comparatively less valuable today (because better alternatives exist, or because the cash flow is riskier), while a LOWER discount rate means the future cash is barely discounted at all. For an entire company, the relevant discount rate is called the "Weighted Average Cost of Capital" (WACC), and the word "weighted" is the key to understanding it: a company is financed by a MIX of two fundamentally different sources of capital — equity (money from shareholders, who bear the most risk and therefore demand the highest expected return, called the "cost of equity") and debt (money from lenders, who take less risk because they are paid before shareholders and therefore demand a lower return, called the "cost of debt") — and WACC blends these two costs together in proportion to how much of the company\'s total capital comes from each source. One crucial wrinkle: interest paid on debt is tax-deductible (it reduces taxable income, just like depreciation does), so the EFFECTIVE cost of debt to the company is lower than the rate lenders actually charge, once this tax shield is accounted for — this is why WACC always uses the AFTER-TAX cost of debt, multiplying the stated interest rate by (1 minus the tax rate) before blending it in. A HIGHER WACC means the market (or the analyst) is treating the company\'s future cash flows as riskier or less certain, which mechanically produces a LOWER present value / valuation for the exact same projected cash flows — WACC and valuation move in opposite directions.',
          core: 'WACC = (equity weight × cost of equity) + (debt weight × after-tax cost of debt), where after-tax cost of debt = pre-tax cost × (1 − tax rate). A higher WACC discounts future cash flows more harshly, producing a LOWER valuation for the same projected cash flows; a lower WACC produces a HIGHER valuation.',
          when: 'Any DCF valuation question, or any question asking you to blend the cost of equity and debt into a single company-wide discount rate.',
          formulas: ['WACC = (E/V)×Re + (D/V)×Rd×(1−t), where V = E+D (total capital), Re = cost of equity, Rd = pre-tax cost of debt, t = tax rate.', 'Cost of equity (CAPM) = risk-free rate + beta × equity risk premium.', 'Discounting a single future cash flow C received n years from now to its present value: PV = C / (1+WACC)ⁿ.'],
          intuition: 'Think of WACC as the "hurdle rate" a company\'s investments must clear to be worth doing at all — if a project is expected to return less than WACC, it destroys value for the people who supplied the capital, even if it looks "profitable" in a simple accounting sense; DCF valuation applies that same hurdle-rate logic to discount the whole company\'s future cash flows back to a present-day price tag.',
          examples: [
            { level: 1, text: 'A company is financed 100% by equity with a cost of equity of 10%. What is its WACC? Since there is no debt at all, WACC simply equals the cost of equity: 10%. This confirms the formula collapses sensibly to a single term when one funding source is absent.' },
            { level: 2, text: 'A company is financed 70% equity (cost of equity 12%) and 30% debt (pre-tax cost of debt 6%, tax rate 25%). First, after-tax cost of debt = 6%×(1−25%) = 4.5%. WACC = 70%×12% + 30%×4.5% = 8.4% + 1.35% = 9.75%. Notice the after-tax cost of debt (4.5%) is meaningfully cheaper than its pre-tax rate (6%) — this is the tax shield at work, and it is why debt is often called "cheaper" capital than equity, even before considering the raw rate difference.' },
            { level: 3, text: 'Two otherwise-identical companies project the exact same $100 cash flow, 5 years from now. Company A has a WACC of 8%; Company B, seen as riskier, has a WACC of 14%. PV for A = 100/(1.08)^5 = 100/1.469 ≈ $68.06. PV for B = 100/(1.14)^5 = 100/1.925 ≈ $51.94. The identical future cash flow is worth over $16 LESS today for the riskier company — this is the direct, quantified consequence of "higher WACC ⇒ lower valuation," and it is exactly why a company\'s perceived riskiness (which raises its cost of equity and/or debt) directly shrinks its DCF-implied value, independent of how good its actual cash flow projections are.' }
          ],
          trap: 'Using the PRE-TAX cost of debt directly in the WACC formula, skipping the after-tax adjustment — this systematically overstates WACC (making debt look more expensive than it truly is to the company) and therefore understates the resulting valuation. Also, confusing "cost of debt" (what lenders demand) with "cost of equity" (what shareholders demand) — these are compensating for very different levels of risk and are never interchangeable.',
          checks: [
            { level: 1, q: 'Why is a dollar received one year from now worth LESS than a dollar today?', options: ['Inflation always destroys exactly one dollar of value per year', 'Because that future dollar could instead have been invested today to grow, and because a future promise carries risk it might not arrive', 'It is not actually worth less — this is a myth', 'Because dollars physically degrade over time'], a: 1, why: 'Both the opportunity cost of not investing it today, and the risk that the future payment does not materialise, justify discounting future cash flows.' },
            { level: 1, q: 'A company is financed 100% by debt, with a pre-tax cost of debt of 8% and a tax rate of 20%. What is its WACC?', options: ['8%', '6.4%', '1.6%', '10%'], a: 1, why: 'With no equity at all, WACC = 100%×after-tax cost of debt = 8%×(1−20%) = 6.4%.' },
            { level: 2, q: 'Why does WACC use the AFTER-TAX cost of debt rather than the rate lenders actually charge?', options: ['Because interest is not really paid in cash', 'Because interest expense is tax-deductible, lowering the company\'s actual cash cost of borrowing below the stated interest rate', 'Because equity is always tax-deductible too', 'There is no difference between pre-tax and after-tax cost of debt'], a: 1, why: 'The interest tax shield genuinely lowers the net cost of debt to the company, and WACC is meant to reflect the TRUE blended cost of capital.' },
            { level: 2, q: 'A company is 60% equity (cost of equity 11%) and 40% debt (after-tax cost of debt 5%). What is WACC?', options: ['8%', '8.6%', '9.2%', '7.4%'], a: 1, why: '60%×11% + 40%×5% = 6.6% + 2.0% = 8.6%.' },
            { level: 3, q: 'All else equal, if a company\'s perceived risk rises (pushing its cost of equity higher), what happens to its DCF-implied valuation?', options: ['Valuation rises, since risk means higher potential reward', 'Valuation falls, since a higher discount rate shrinks the present value of the same future cash flows', 'No effect — WACC does not affect valuation, only cash flows do', 'It depends only on the tax rate'], a: 1, why: 'A higher cost of equity raises WACC, and a higher WACC discounts every future cash flow more harshly, mechanically lowering the DCF valuation for identical projected cash flows.' },
            { level: 3, q: 'Two projects both promise $200 in 3 years. Project X is discounted at 6%, Project Y at 15%. Roughly how much LESS is Project Y worth today, versus Project X?', options: ['They are worth the same today', 'Project Y is worth more today', 'Project Y is worth meaningfully less today — roughly $168 vs $131, a difference of about $37', 'The difference cannot be estimated without more information'], a: 2, why: '200/(1.06)³ ≈ $168; 200/(1.15)³ ≈ $131 — a real, sizeable gap purely from the discount rate, illustrating how much a company\'s perceived risk can move its valuation.' }
          ]
        },
        {
          id: 'ibb2', name: 'Terminal value: valuing the cash flows you cannot possibly project one by one, forever',
          primer: 'A DCF model explicitly projects a company\'s cash flows for only a handful of years into the future — typically 5 to 10 — because trying to forecast the EXACT cash flow of year 47 with any real precision is obviously hopeless; nobody can predict that far ahead with confidence. But a healthy company is not expected to simply STOP existing (and stop generating cash) the moment the explicit projection period ends — so a DCF needs some way to capture the value of ALL the cash flows that will arrive after the projection window closes, lumped together into a single number called the "terminal value," calculated as of the END of the final explicitly projected year. There are two standard, widely accepted methods for estimating terminal value, and it is worth understanding both, because they approach the same problem from genuinely different angles. The "Gordon growth" (or "perpetuity growth") method treats everything after the projection period as an infinite, ever-growing stream of cash flow growing at some modest, sustainable long-run rate FOREVER (typically close to long-run GDP growth, since no company can outgrow the entire economy forever) — it uses the perpetuity formula from basic finance, TV = FCF_final×(1+g) / (WACC−g), which requires growing the final explicit year\'s cash flow by one more year of growth before dividing by the gap between WACC and that growth rate. The "exit multiple" method instead assumes that at the end of the projection period, the company could simply be SOLD to another buyer at a valuation multiple (like EV/EBITDA) similar to what comparable companies trade at TODAY — it is really a comps valuation, just applied at a future point in time rather than today, computed as TV = final-year EBITDA × exit multiple. Whichever method produces the terminal value, that terminal value is itself just a large lump sum sitting at the end of the projection period, so it must ALSO be discounted back to today\'s present value using the exact same WACC-based discounting as every other projected cash flow, using the SAME number of years as the final explicit cash flow.',
          core: 'Terminal value captures everything beyond the explicit projection period, valued as of the end of the final projected year. Gordon growth method: TV = FCF_final×(1+g)/(WACC−g), assuming perpetual modest growth. Exit multiple method: TV = final-year EBITDA × an assumed future trading multiple. Either way, the terminal value must then be discounted back to today just like any other cash flow.',
          when: 'Any DCF question involving cash flows beyond the explicit projection period, or any "how do you value everything after year N" question.',
          formulas: ['Gordon growth terminal value = FCF_final × (1+g) / (WACC − g), where g is the assumed perpetual long-run growth rate (must be strictly less than WACC).', 'Exit multiple terminal value = final projected year EBITDA × assumed exit EV/EBITDA multiple.', 'Present value of the terminal value = TV / (1+WACC)ⁿ, where n = the number of years from today to the end of the final projected year (the same year the TV is computed as of).'],
          intuition: 'It is a striking and important fact in real DCF models that the terminal value often makes up the MAJORITY of a company\'s total implied enterprise value — sometimes 60-80% of it — precisely because it is meant to capture "everything from year 6 or 11 onward, forever." This is exactly why terminal value assumptions (the long-run growth rate, or the assumed future exit multiple) deserve as much scrutiny as the explicit-period forecasts, if not more.',
          examples: [
            { level: 1, text: 'Final projected year FCF is $50m, long-run growth is 2%, WACC is 9%. Gordon growth TV = 50×(1.02)/(0.09−0.02) = 51/0.07 ≈ $728.6m. Notice how a modest-looking 2% growth rate, divided into a modest-looking 7% gap, produces a terminal value nearly 15× the final year\'s cash flow — perpetuity math compounds this way precisely because "forever" is a very long time.' },
            { level: 2, text: 'Same final year, but using the exit multiple method instead: final year EBITDA is $90m, and comparable companies trade at 9× EV/EBITDA. Exit multiple TV = 90×9 = $810m — notice this is a different, independently-derived number from the Gordon growth answer above; the two methods will rarely match exactly, and getting a broadly similar answer from both is often used as a sanity check on the assumptions.' },
            { level: 3, text: 'A terminal value of $800m is computed as of the end of year 5. WACC is 10%. What is its value today? PV = 800/(1.10)^5 = 800/1.611 ≈ $496.7m. Notice that even though $800m looks like a large number, discounting it back 5 years at a meaningful WACC shrinks it by nearly 40% — this is exactly why the CHOICE of WACC has such an outsized effect on a DCF\'s final answer: it discounts not just the explicit cash flows, but this large terminal value too.' }
          ],
          trap: 'Forgetting to grow the final projected year\'s cash flow by one more year of growth (the "×(1+g)" term) before applying the Gordon growth formula — this is a very common off-by-one-year error that understates the terminal value. A second, equally common trap: discounting the terminal value back by the WRONG number of years — it must be discounted by the same number of years as the FINAL explicit cash flow, since that is when it is calculated as of, not one year more or less.',
          checks: [
            { level: 1, q: 'Why does a DCF need a "terminal value" at all?', options: ['Because companies always go bankrupt after the projection period', 'Because it is impractical to explicitly project cash flows individually forever, so everything beyond the projection window is captured in one lump-sum estimate', 'Because terminal value is required by accounting law', 'It is optional and rarely used in practice'], a: 1, why: 'Explicit forecasts are only credible for a handful of years; terminal value captures the remaining, much longer future in a single estimate.' },
            { level: 1, q: 'The Gordon growth method assumes cash flows grow:', options: ['At a wildly different rate every year, forever', 'At one modest, constant rate, forever', 'Only for the explicit projection period, then stop entirely', 'At the same rate as inflation only'], a: 1, why: 'The perpetuity growth formula specifically assumes a single constant long-run growth rate continuing indefinitely.' },
            { level: 2, q: 'Final year FCF = $40m, growth = 2.5%, WACC = 10%. What is the Gordon growth terminal value (nearest $m)?', options: ['$533m', '$547m', '$400m', '$500m'], a: 1, why: 'TV = 40×1.025/(0.10−0.025) = 41/0.075 ≈ $546.7m ≈ $547m.' },
            { level: 2, q: 'Final year EBITDA = $70m, exit multiple = 8×. What is the exit-multiple terminal value?', options: ['$560m', '$78m', '$8.75m', '$700m'], a: 0, why: 'TV = 70×8 = $560m.' },
            { level: 3, q: 'A terminal value of $600m is computed as of the end of year 6. WACC is 9%. What is its present value today (nearest $m)?', options: ['$550m', '$358m', '$471m', '$600m'], a: 1, why: 'PV = 600/(1.09)^6 = 600/1.677 ≈ $357.8m ≈ $358m — discount by exactly 6 years, matching when the TV is computed as of.' },
            { level: 3, q: 'Why does terminal value often make up the majority of a DCF\'s total implied value?', options: ['It never actually makes up more than a small fraction', 'Because it represents an infinite (or very long) stream of future cash flows collapsed into one number, and perpetuity math compounds substantially over "forever"', 'Because analysts always deliberately inflate it', 'Because explicit-period cash flows are always negative'], a: 1, why: 'Capturing "everything from year N+1 onward, forever" in one number naturally produces a large figure relative to just a handful of explicit years, especially when growth is close to the discount rate.' }
          ]
        }
      ]
    },

    /* =============================== IB-C =============================== */
    {
      unit: 'IB-C', topic: 'Comps & Precedents', title: 'Relative valuation: comparable companies and precedent transactions', track: 'ib', concepts: [
        {
          id: 'ibc1', name: 'Trading comps: valuing a company by what similar companies are worth right now',
          primer: 'A DCF values a company from first principles, by projecting its own cash flows and discounting them — but this is slow, and every assumption (growth, margins, WACC) is a judgment call an analyst could get wrong. "Comparable companies analysis" (almost always shortened to "comps" or "trading comps") takes a completely different, faster approach: find a handful of OTHER publicly-traded companies that are similar to the target in industry, size, growth profile and risk, look at what MULTIPLE of some financial metric (most commonly EV/EBITDA, but also EV/Revenue or P/E) those comparable companies currently trade at in the market, and apply that same multiple to the target company\'s own metric to estimate what the target should be worth. The entire method rests on a simple, powerful assumption: similar businesses, facing similar growth prospects and risks, should trade at broadly similar valuation multiples — if a target looks meaningfully cheaper or more expensive than its true peers on this basis, that difference itself becomes an interesting question (is the target genuinely undervalued, or is there a real reason — worse growth, more risk, weaker margins — that justifies trading at a discount?). Because real-world peer sets always include some companies that are unusually cheap or unusually expensive for reasons that have nothing to do with the target (a one-off event, an accounting quirk, a temporary market overreaction), analysts almost always use the MEDIAN multiple across the peer group rather than the simple average (mean) — the median is far more resistant to being dragged around by one or two extreme outlier companies, exactly the same statistical reason the median is preferred over the mean when summarising incomes or house prices in the real world. Once the appropriate multiple (usually the peer median) is selected, applying it is simple arithmetic: implied Enterprise Value = chosen multiple × the target\'s own value of that same metric, which can then be converted into an implied equity value and share price using the same EV-to-equity bridge covered elsewhere in this track.',
          core: 'Trading comps value a company by applying a peer group\'s valuation multiple (usually the MEDIAN EV/EBITDA, to resist distortion from outliers) to the target\'s own metric: implied EV = peer median multiple × target\'s metric.',
          when: 'Any "value this company using comparable companies / trading multiples" question, or any question asking you to summarise a set of peer multiples.',
          formulas: ['Implied EV = peer median multiple × target\'s own metric (e.g. EBITDA).', 'Median of an odd-sized sorted list = the single middle value; median of an even-sized sorted list = the average of the two middle values.', 'Once implied EV is found, convert to equity value and share price using the standard EV-to-equity bridge (subtract net debt, preferred, minority interest; divide by diluted shares).'],
          intuition: 'Comps analysis is really asking the market itself to do the valuation work for you: instead of building your own opinion of the "right" discount rate and growth assumptions from scratch, you borrow the collective judgment already embedded in how investors are currently pricing similar businesses.',
          examples: [
            { level: 1, text: 'Five peers trade at EV/EBITDA multiples of 6×, 7×, 8×, 9×, and 20× (the last one is a clear outlier, perhaps due to a recent takeover rumour inflating its price). The simple average is (6+7+8+9+20)/5 = 10.0×, badly distorted by the outlier. The median (sort: 6,7,8,9,20 — middle value) is 8×, a far more representative "typical" multiple for the peer group, unaffected by the one extreme value.' },
            { level: 2, text: 'Using the median multiple of 8× from above, and a target with $50m of EBITDA: implied EV = 8× × $50m = $400m.' },
            { level: 3, text: 'The same target has $60m of net debt and 20m diluted shares. What is the implied share price? Equity value = EV − net debt = 400 − 60 = $340m. Share price = 340/20 = $17.00. This shows the full comps-to-price workflow: pick the multiple (median), apply it to get EV, then bridge from EV down to a per-share figure — comps analysis on its own only gets you to enterprise value; the EV-to-equity bridge is a separate, necessary second step.' }
          ],
          trap: 'Using the simple average (mean) of peer multiples instead of the median — a single outlier peer (due to a takeover rumour, a one-off accounting item, or simply being a much larger or smaller company than the others) can distort the mean substantially, while the median stays anchored to the "typical" company in the set.',
          checks: [
            { level: 1, q: 'Comps analysis values a company by:', options: ['Projecting its own cash flows and discounting them', 'Applying a peer group\'s trading multiple to the target\'s own metric', 'Only using its historical stock price', 'Averaging its assets and liabilities'], a: 1, why: 'Comps is a RELATIVE valuation method, benchmarking the target against what similar public companies currently trade at.' },
            { level: 1, q: 'Why is the median usually preferred over the mean (simple average) when summarising a set of peer multiples?', options: ['The median is always a larger number', 'The median is much less distorted by one or two extreme outlier peers', 'The mean is illegal to use in finance', 'They always give the same answer anyway'], a: 1, why: 'A single unusually cheap or expensive peer can drag the mean far from what is "typical," while the median stays close to the middle of the pack.' },
            { level: 2, q: 'Peers trade at 5×, 6×, 6×, 9×, 14×. What is the median?', options: ['8×', '6×', '9×', '6.67×'], a: 1, why: 'Already sorted; the middle (3rd of 5) value is 6×.' },
            { level: 2, q: 'Using an 8× median multiple and a target with $35m EBITDA, what is the implied EV?', options: ['$280m', '$43m', '$4.375m', '$35m'], a: 0, why: 'Implied EV = 8× × $35m = $280m.' },
            { level: 3, q: 'A comps analysis produces an implied EV of $500m. To get to an implied SHARE PRICE, what must you still do?', options: ['Nothing further — EV and share price are the same thing', 'Subtract net debt (and preferred/minority interest) to get equity value, then divide by diluted shares', 'Multiply by the tax rate', 'Divide by EBITDA again'], a: 1, why: 'Comps only produces enterprise value directly; converting to a per-share figure always requires the separate EV-to-equity bridge.' },
            { level: 3, q: 'A peer set has 6 companies (even number) trading at 5×, 6×, 7×, 9×, 10×, 15×. What is the median?', options: ['8×', '7×', '9×', '8.67×'], a: 0, why: 'With an even count, the median is the average of the two middle values (3rd and 4th): (7+9)/2 = 8×.' }
          ]
        }
      ]
    },

    /* =============================== IB-D =============================== */
    {
      unit: 'IB-D', topic: 'M&A Mechanics', title: 'Merger models: why the market rewards or punishes a deal', track: 'ib', concepts: [
        {
          id: 'ibd1', name: 'Accretion and dilution: what it means, and why the market does not just reward "bigger"', track: 'ib',
          primer: 'When one company (the "acquirer") buys another (the "target"), the immediate, mechanical question a merger model answers is: does the acquirer\'s earnings per share (EPS) go UP or DOWN as a direct result of the deal? If combined pro-forma EPS after the deal is HIGHER than the acquirer\'s standalone EPS before the deal, the deal is called "accretive." If pro-forma EPS is LOWER, the deal is "dilutive." The crucial, easy-to-miss point is that this is a comparison of PER-SHARE earnings, not total earnings — a deal can straightforwardly increase the acquirer\'s total combined net income (after all, you are simply adding the target\'s profit to your own) while STILL being dilutive on a per-share basis, if the number of new shares issued to fund the deal grows FASTER than the combined earnings do. This matters enormously in practice because the stock market reacts very strongly, very quickly, to whether a newly announced deal appears accretive or dilutive — an accretive deal is generally (though not always, and not automatically) seen as a signal that the acquirer got the target for a "cheap enough" price relative to its own valuation, while a dilutive deal raises an immediate question: why is management willing to shrink earnings per existing shareholder\'s share? Whether a deal ends up accretive or dilutive depends heavily on HOW it is financed. An all-CASH deal (funded from the acquirer\'s existing cash balance) issues no new shares at all, so the share count does not grow — the deal is accretive as long as the target\'s earnings yield (net income / purchase price) exceeds the after-tax opportunity cost of the cash used (the return that cash was otherwise earning). An all-STOCK deal issues new acquirer shares to pay the target\'s shareholders, diluting the share count directly, so accretion depends on whether the target\'s earnings yield exceeds the acquirer\'s own earnings yield (a rough rule of thumb: buying a company at a LOWER P/E than your own tends to be accretive; buying at a HIGHER P/E than your own tends to be dilutive). Crucially, a dilutive deal is not automatically a BAD deal — a management team might rationally accept short-term EPS dilution if the strategic logic is strong enough: entering a valuable new market, eliminating a dangerous competitor, acquiring technology or talent that could not otherwise be built in time, or unlocking cost synergies that will make the deal accretive again within a year or two even though it is dilutive on day one.',
          core: 'A deal is accretive if pro-forma combined EPS exceeds the acquirer\'s standalone EPS, dilutive if it is lower — this is a PER-SHARE comparison, not a total-earnings comparison. Financing matters: cash deals avoid new share issuance; stock deals dilute the share count directly, roughly favouring accretion when the target trades at a lower P/E than the acquirer. Dilutive deals are not automatically bad if the strategic logic (synergies, market access, competitive necessity) justifies the short-term EPS cost.',
          when: 'Any merger-model question asking whether a deal is accretive or dilutive, or any question about why the market reacts positively or negatively to an M&A announcement.',
          formulas: ['Accretion/dilution % = (Pro-forma EPS / acquirer standalone EPS − 1) × 100.', 'All-stock deal: exchange ratio = deal price per target share / acquirer\'s share price. New shares issued = target\'s share count × exchange ratio.', 'Pro-forma EPS = combined net income (acquirer + target, net of any new financing costs and synergies) / (acquirer\'s original shares + newly issued shares).'],
          intuition: 'Picture EPS as "profit sliced into portions, one portion per existing share" — an accretive deal means each EXISTING slice gets a little bigger after the deal; a dilutive deal means the pie grew, but it also got cut into so many MORE slices that each individual slice actually shrank.',
          examples: [
            { level: 1, text: 'Acquirer has $100m net income and 50m shares (EPS = $2.00). It buys a target for cash (no new shares issued), adding $20m of net income with no other adjustments. Combined net income = $120m, shares stay at 50m. Pro-forma EPS = 120/50 = $2.40. This is accretive: EPS rose from $2.00 to $2.40, a +20% change — an all-cash deal, with no financing cost assumed, is accretive here simply because it adds profit without adding any new shares.' },
            { level: 2, text: 'Same acquirer ($100m NI, 50m shares, EPS $2.00) instead does an all-STOCK deal, issuing 30m new shares to acquire a target that adds $20m of net income. Combined net income = $120m. New share count = 50+30 = 80m. Pro-forma EPS = 120/80 = $1.50. This is DILUTIVE — EPS fell from $2.00 to $1.50, a −25% change — even though total combined net income rose by $20m, because the share count grew by 60% (from 50m to 80m), far outpacing the 20% growth in net income.' },
            { level: 3, text: 'Why did the cash deal in the first example accrete while the stock deal in the second example diluted, even though both added the exact same $20m of target net income? The difference is entirely in the denominator: the cash deal added zero new shares, so 100% of the extra $20m flowed straight to existing shareholders\' per-share earnings. The stock deal added 30m new shares (a 60% increase to the share count) to fund the purchase, and that dramatic increase in the number of slices outweighed the increase in the size of the pie. This illustrates the core lesson: financing structure, not just the target\'s profitability, drives whether a deal is accretive or dilutive.' }
          ],
          trap: 'Assuming that because combined net income rose, the deal must be "good" or accretive — always check the PER-SHARE figure, since a large new share issuance can turn a genuinely profit-boosting acquisition into an EPS-dilutive one. The reverse trap also matters: assuming a dilutive deal is automatically a bad decision, when strong-enough strategic rationale (synergies, market access, competitive necessity) can justify short-term dilution.',
          checks: [
            { level: 1, q: 'A deal is "accretive" when:', options: ['Total combined net income rises', 'Pro-forma EPS is higher than the acquirer\'s standalone EPS', 'The acquirer pays entirely in cash', 'The target\'s revenue is larger than the acquirer\'s'], a: 1, why: 'Accretion/dilution is specifically a per-share comparison, not a total-earnings or deal-structure comparison.' },
            { level: 1, q: 'Is it possible for combined net income to rise while EPS still falls?', options: ['No, that is a contradiction', 'Yes — if new shares are issued fast enough, per-share earnings can fall even as total earnings rise', 'Only if the target has negative net income', 'Only in an all-cash deal'], a: 1, why: 'This is exactly the mechanism of dilution in a stock-funded deal: the earnings pie grows, but it is sliced into even more pieces.' },
            { level: 2, q: 'Acquirer: $80m net income, 40m shares. All-cash deal adds $15m of net income with no new shares issued. What is the new EPS, and is it accretive or dilutive?', options: ['$2.375, accretive', '$2.00, no change', '$1.90, dilutive', '$2.375, dilutive'], a: 0, why: 'New EPS = (80+15)/40 = $2.375, up from 80/40 = $2.00 — accretive.' },
            { level: 2, q: 'All-stock deal roughly favours accretion when:', options: ['The target trades at a HIGHER P/E than the acquirer', 'The target trades at a LOWER P/E than the acquirer', 'P/E is irrelevant to accretion/dilution', 'The acquirer has more total debt than the target'], a: 1, why: 'Buying earnings "cheaply" (at a lower P/E than your own) in stock tends to be accretive, since you are issuing relatively fewer of your (expensively-valued) shares per dollar of acquired earnings.' },
            { level: 3, q: 'A board approves a dilutive stock deal despite the EPS hit. Which is the STRONGEST justification?', options: ['Dilutive deals are always secretly accretive if you wait long enough, with no further explanation needed', 'The deal provides critical technology/market access/cost synergies whose value is not yet reflected in near-term EPS', 'The target\'s CEO insisted on it', 'Dilution never matters to any stakeholder'], a: 1, why: 'Legitimate strategic rationale — synergies, competitive necessity, capability that could not otherwise be built in time — can outweigh a short-term EPS cost; simply asserting deals "become accretive eventually" with no mechanism is not a justification.' },
            { level: 3, q: 'Acquirer EPS is $3.00. A stock deal results in pro-forma EPS of $2.70. What is the accretion/dilution percentage?', options: ['+10%', '−10%', '−30%', '+30%'], a: 1, why: '(2.70/3.00 − 1) × 100 = −10% — a 10% dilutive deal.' }
          ]
        }
      ]
    },

    /* =============================== IB-E =============================== */
    {
      unit: 'IB-E', topic: 'LBO', title: 'Leveraged buyouts: how borrowed money changes the math of a return', track: 'ib', concepts: [
        {
          id: 'ibe1', name: 'Sources and uses, and why leverage is the whole point of an LBO',
          primer: 'A leveraged buyout ("LBO") is the purchase of a company financed with a large amount of borrowed money (debt) alongside a smaller slice of the buyer\'s own cash (equity) — the word "leveraged" refers directly to this heavy use of debt, or "leverage," to fund the purchase. The private equity firm doing the buying is usually called the "sponsor." Every LBO can be summarised with a simple "sources and uses" table: the "uses" side lists everything the money is needed FOR (overwhelmingly, this is the purchase price of the company itself, often called the purchase enterprise value, plus transaction fees); the "sources" side lists everywhere the money comes FROM to cover those uses (a large slice of new debt raised against the target company, plus the sponsor\'s own equity check, which mathematically must be whatever is left over once debt is subtracted — sources and uses must always balance exactly, by definition). Why go to the trouble of borrowing so much money, rather than simply paying all-cash from the sponsor\'s own funds? Because leverage dramatically amplifies the RETURN on the sponsor\'s own invested capital, for a given amount of value growth — this is the single most important intuition in all of LBO analysis. If a company is bought entirely with the sponsor\'s own cash and later sold for a higher price, the sponsor\'s percentage return simply equals the percentage growth in the company\'s value. But if the same company is bought using mostly borrowed money, the SAME dollar amount of value growth accrues almost entirely to the much SMALLER equity check the sponsor actually put in — the lenders who provided the debt do not get any extra upside if the company does well (they were promised a fixed return, not a share of the growth), so all of the "excess" appreciation flows disproportionately to the equity holder. This amplification effect cuts both ways, however: leverage also magnifies LOSSES in the same proportion, which is exactly why heavily-levered companies are considered financially riskier — a modest decline in company value can wipe out a highly-levered equity position entirely, even while the same decline would only modestly dent an all-equity-funded purchase.',
          core: 'Sources (debt raised + sponsor equity) must equal uses (purchase price + fees). Using a large proportion of debt shrinks the sponsor\'s own equity check for the same purchase price, so a given amount of dollar value growth translates into a much larger PERCENTAGE return on that smaller equity base — leverage amplifies both gains and losses.',
          when: 'Any LBO question about how a deal is financed, or any question asking WHY leverage boosts (or endangers) private equity returns.',
          formulas: ['Uses: Purchase enterprise value = entry EV/EBITDA multiple × EBITDA (plus any transaction fees).', 'Sources: Debt = leverage multiple × EBITDA (a separate multiple from the entry purchase multiple). Sponsor equity = total uses − debt raised (the "plug" that balances the table).', 'Leverage amplification (intuition check): a smaller equity base means the SAME dollar gain in company value produces a LARGER percentage return on that equity.'],
          intuition: 'Think of buying a $1,000,000 house with a $900,000 mortgage and only $100,000 of your own cash: if the house rises in value by $100,000 (10% of its price), your own $100,000 investment has DOUBLED — a 100% return — even though the underlying asset only grew 10%. LBOs apply exactly this same mortgage-style amplification to buying companies instead of houses.',
          examples: [
            { level: 1, text: 'A sponsor buys a company for 8× its $50m EBITDA ($400m purchase price), financed with debt of 5× EBITDA ($250m). Sponsor equity (the plug) = 400 − 250 = $150m.' },
            { level: 2, text: 'Suppose that company is sold 5 years later for exactly the same $400m enterprise value (no EBITDA growth, no multiple change), but $100m of the original $250m debt has been paid down using the company\'s free cash flow over those 5 years, leaving $150m of debt outstanding. Exit equity value = exit EV − remaining debt = 400 − 150 = $250m. MOIC (multiple of invested capital) = exit equity / entry equity = 250/150 ≈ 1.67×. Notice the underlying business did not grow in value at ALL (still worth $400m) — the entire 1.67× return came purely from paying down debt with the company\'s own cash flow, converting debt into equity value over time. This is the "deleveraging" return driver, distinct from business growth.' },
            { level: 3, text: 'Compare that same $150m of value growth (from $400m purchase EV rising, hypothetically, to $550m at exit with debt fully repaid, i.e. exit equity = $550m) under two different financing structures: (a) an all-cash purchase (equity = full $400m, no debt): return = 550/400 = 1.375× MOIC. (b) The levered purchase from above (equity = $150m): if the same $150m of value growth accrued and debt was fully repaid, exit equity = 550−0 = $550m, MOIC = 550/150 ≈ 3.67×. The identical $150m of dollar-value growth produces a 37.5% return in the unlevered case but a return of nearly 267% in the levered case — this stark contrast is the entire reason leverage is central to how private equity generates outsized returns.' }
          ],
          trap: 'Comparing exit EQUITY value to entry ENTERPRISE value (or vice versa) when computing a return — MOIC must always compare equity-to-equity, since the sponsor only owns the equity slice, not the whole enterprise value (debt holders have their own separate, fixed claim and do not share in the equity upside).',
          checks: [
            { level: 1, q: 'In "sources and uses," what must always be true?', options: ['Sources exceed uses by the amount of fees', 'Sources and uses must exactly balance', 'Uses always exceed sources', 'There is no required relationship between them'], a: 1, why: 'Every dollar of "use" (what the money is needed for) must be funded by exactly one dollar of "source" (where the money comes from) — they balance by definition.' },
            { level: 1, q: 'Why do private equity sponsors use a large amount of debt rather than paying all-cash?', options: ['Debt is required by law for all acquisitions', 'Leverage amplifies the percentage return on the sponsor\'s smaller equity check, for the same dollar amount of value growth', 'It has no effect on returns at all', 'Debt eliminates all financial risk'], a: 1, why: 'A smaller equity base means the same dollar gain in enterprise value translates into a much larger percentage return on that equity — the central mechanic of leveraged returns.' },
            { level: 2, q: 'Purchase price is 7× a $60m EBITDA, financed with debt of 4× EBITDA. What is the required sponsor equity?', options: ['$420m', '$240m', '$180m', '$60m'], a: 2, why: 'Purchase EV = 7×60 = $420m. Debt = 4×60 = $240m. Sponsor equity = 420−240 = $180m.' },
            { level: 2, q: 'Entry equity was $150m; exit equity value is $300m. What is the MOIC?', options: ['1.5×', '2.0×', '0.5×', '3.0×'], a: 1, why: 'MOIC = exit equity / entry equity = 300/150 = 2.0×.' },
            { level: 3, q: 'A company\'s enterprise value does not change at all over the hold period, yet the sponsor still earns a positive MOIC above 1.0×. What is the most likely explanation?', options: ['This is impossible — MOIC must equal 1.0× if EV is unchanged', 'Debt was paid down using the company\'s free cash flow during the hold, converting debt into equity value even with flat EV', 'The exit multiple must secretly have expanded', 'EBITDA must have grown'], a: 1, why: 'Deleveraging (paying down debt with the company\'s own cash flow) is itself a distinct source of equity value growth, entirely separate from EBITDA growth or multiple expansion — flat enterprise value with debt paydown still produces a return above 1.0×.' },
            { level: 3, q: 'Why is comparing exit EQUITY value to entry ENTERPRISE value (instead of entry equity) the wrong way to compute a sponsor\'s return?', options: ['It actually is the correct method', 'The sponsor only invested the entry EQUITY check (not the whole enterprise value, most of which was debt), so the return must be measured against that actual equity investment', 'Enterprise value and equity value are always identical', 'Debt holders share equally in the sponsor\'s return'], a: 1, why: 'MOIC measures the return on what the sponsor actually put IN (the equity check), not the total transaction size, most of which was funded by lenders with their own separate, fixed claim.' }
          ]
        }
      ]
    }
  ];

  global.QTL_LESSONS_IB = L;
})(window);
